from pathlib import Path
import json,math,html
root=Path('artifacts');b=json.loads((root/'airport-survey-baseline.json').read_text(encoding='utf-8'));d=json.loads((root/'airport-detail-survey.json').read_text(encoding='utf-8'));cs=json.loads((root/'airport-candidates-surveyed.json').read_text(encoding='utf-8'));site=next(v for v in cs if v['x']==6800 and v['z']==1900)
box=dict(min_x=6612,max_x=6988,min_z=1332,max_z=2468);area=376*1136;covered=0
for t in b['tiles']['items']:
 q=t['bounds'];covered+=max(0,min(q['max_x'],box['max_x'])-max(q['min_x'],box['min_x']))*max(0,min(q['max_z'],box['max_z'])-max(q['min_z'],box['min_z']))
assert abs(covered-area)<1
heights=[x['height_m'] for x in site['terrain']['items']];site['height_range']=[min(heights),max(heights)];site['owned_area_m2']=covered
plan={'status':'conceptual_not_native_previewed','site':site,'bounds':box,'prefab':'Airport01','orientation_intent':'long_axis_north_south_terminal_west','rotation_degrees':None,'rotation_source':'unresolved','placement_status':'conceptual','building_cost':750000,'road_corridors':[[{'x':6500,'z':1600},{'x':6600,'z':1600}],[{'x':6600,'z':1400},{'x':6600,'z':2400}]],'noise_buffer_m':1000,'noise_buffer_is_planning_assumption':True,'surveys':d,'requires':['Native terminal/road candidate binding after road planning','Detailed grading and full native airport/subobject collision preview','Exact boundary power/water/sewage capacities','Air outside connection and route setup','Post-operation noise check at nearest residential and school receptors']}
(root/'auburn-airport-plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2),encoding='utf-8')
P=lambda x,z:(x,-z)
svg=['<svg id="airport-map" viewBox="4400 -3100 2900 3100" aria-label="机场选址和已购地图" role="img"><rect x="-8000" y="-8000" width="16000" height="16000" fill="#e9edf0"/>']
for t in b['tiles']['items']:
 q=t['bounds'];svg.append(f'<rect x="{q["min_x"]}" y="{-q["max_z"]}" width="{q["max_x"]-q["min_x"]}" height="{q["max_z"]-q["min_z"]}" fill="#eef3e8" stroke="#ccd4c4" stroke-width="5"/>')
# Rounded rectangle is the 1 km distance envelope of the reserved footprint.
svg.append('<rect x="5612" y="-3468" width="2376" height="3136" rx="1000" fill="#eab64b" fill-opacity=".09" stroke="#bf9343" stroke-dasharray="24 15" stroke-width="6"/>')
for layer,color in [('roads','#6d7d85'),('tracks','#735844'),('utilities','#b880a5')]:
 for r in b['snapshot'][layer]:
  if 'curve' not in r:continue
  c=r['curve'];p=[P(c[k]['x'],c[k]['z']) for k in 'abcd'];svg.append(f'<path d="M{p[0][0]},{p[0][1]} C{p[1][0]},{p[1][1]} {p[2][0]},{p[2][1]} {p[3][0]},{p[3][1]}" fill="none" stroke="{color}" stroke-width="{max(5,r.get("width_m",5))}"/>')
for x in b['snapshot']['buildings']:
 p=x['position'];color='#438865' if x['kind']=='residential' else '#a3afb1';svg.append(f'<circle cx="{p["x"]}" cy="{-p["z"]}" r="12" fill="{color}"/>')
svg.append('<rect x="6612" y="-2468" width="376" height="1136" fill="#50a9b5" fill-opacity=".4" stroke="#125d70" stroke-width="8"/><text x="6800" y="-1910" font-size="40" text-anchor="middle" fill="#0a4557" transform="rotate(90 6800 -1910)">机场占地预留 · 1136 × 376 m</text>')
for pts in plan['road_corridors']:
 svg.append('<polyline points="'+' '.join(f'{p["x"]},{-p["z"]}' for p in pts)+'" fill="none" stroke="#d26c32" stroke-width="24" stroke-dasharray="35 12"/>')
for x,z,t in [(6200,2520,'八角城镇'),(6640,2600,'推荐机场地块 A'),(5940,1100,'既有铁路'),(6000,800,'沿既有桥梁去高速立交'),(6610,1500,'新建机场专用路'),(4850,2350,'住宅'),(5850,3000,'1 km 不新增敏感用地缓冲线')]:svg.append(f'<text x="{x}" y="{-z}" font-size="35" fill="#203e47" stroke="#f5f7f0" stroke-width="7" paint-order="stroke">{t}</text>')
svg.append('</svg>')
page=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>奥本山 · 机场选址方案</title><style>body{{background:#eef2ed;color:#213d45;font:16px/1.7 system-ui;margin:0}}main{{max-width:1180px;margin:auto;padding:32px}}section{{background:white;padding:25px;margin:22px 0;border-radius:14px}}h1{{font-size:36px}}svg{{width:100%;max-height:900px}}button{{padding:10px;margin:6px;cursor:pointer}}table{{border-collapse:collapse;width:100%}}td,th{{text-align:left;border-bottom:1px solid #ddd;padding:10px}}.note{{color:#6b7677}}a{{color:#126d83}}</style><main><small>奥本山 / 已购区域 / 选址规划，未施工</small><h1>推荐在八角城镇东侧建设普通机场</h1><p>选址中心 X=6800、Z=1900；位于铁路以北，机场长轴南北向，航站楼入口优先朝西。利用现有东侧连接路和高速立交，机场车流无需穿过住宅片区。</p><section><h2>用地与接路</h2><button onclick="document.querySelector('#airport-map').setAttribute('viewBox','4400 -3600 3300 3600')">机场与八角城镇</button><button onclick="document.querySelector('#airport-map').setAttribute('viewBox','-3600 -3600 11000 8000')">全部已购区域</button>{''.join(svg)}<p class="note">浅绿方格为已购土地，绿色点为现有住宅，蓝框为机场占地预留，橙色虚线为规划道路，黄色虚线为 1 km 规划缓冲线。缓冲线不是模拟噪音等值线；规划机场未精确绑定朝向、航站楼入口和道路。</p></section><section><h2>选址核查</h2><table><tr><td>机场资产</td><td>Airport01，已解锁；约 1,136 × 376 米，建筑费 750,000</td></tr><tr><td>用地范围</td><td>X=6612–6988，Z=1332–2468；42.71 公顷，占地矩形全部位于已购土地内</td></tr><tr><td>住宅距离</td><td>机场占地边界至最近当前住宅约 {site['residential_clearance_m']/1000:.2f} km；按建筑保守包围范围估算</td></tr><tr><td>水域</td><td>32 米网格共 432 个样本，未命中地表水；施工前细化边界检查</td></tr><tr><td>地形</td><td>45 点采样约 {min(heights):.1f}–{max(heights):.1f} 米，高差 {site['relief']:.1f} 米；必须先做整地方案，标高尚未确定</td></tr><tr><td>道路方案</td><td>从现有东侧连接路约 (6500,1600) 引出 100 米联络路，接 X≈6600 的南北航站楼前路，长度约 1 km；原有跨铁路桥和高速立交继续使用</td></tr><tr><td>铁路关系</td><td>机场南边界距既有铁路中心线约 187 米；新建连接走廊在铁路北侧，不新增平交道口</td></tr></table></section><section><h2>如何尽量避免噪音影响居民</h2><p>机场占地外 1 km 内不新增住宅、学校、医院等敏感用地，保留空地与交通配套。航站楼车流通过东侧连接路走高速，避免经过西侧住宅。跑道长轴与八角城镇东西向错开；实际航路和进离场路径需按原生资产检查。</p><p>现状机场中心噪音读数为 0，仅是未建机场的基线，不能证明建成后无噪音。1 km 是本方案保守预留，不是已验证的游戏噪音传播阈值；绿化也不能作为消除噪音的保证。投运后必须检查最近住宅和学校的噪音图层，再决定是否需要扩大隔离或调整运营。</p></section><section><h2>备选与施工前条件</h2><p>更北的东侧备选中心 (6800,2200) 高差约 17.7 米，距住宅约 1.02 km，但更靠近北侧水域；保留为备选。西侧 (3600,1800) 水域采样有 36/108 个命中；南侧山区部分候选高差超过 130 米，均不优先。</p><p>本次完成的是选址和接路走廊。还需确认航站楼准确入口、全部跑道与附属设施碰撞、细化整地、道路坡度、水电污水容量，以及航空外部连接和线路。道路、整地及管网费用不包含在 75 万建筑费内。本轮没有建设、拆除或整地。</p><a href="auburn-airport-plan.json">结构化规划与实测数据</a> · <a href="auburn-octagon-town.html">返回八角城镇</a></section></main></html>'''
(root/'auburn-airport-plan.html').write_text(page,encoding='utf-8');print('Airport plan created; owned footprint',covered,'m2; terrain',min(heights),max(heights))
