from pathlib import Path
import json,math,html
q=json.loads(Path('plans/auburn-octagon-town.json').read_text(encoding='utf-8'));a=json.loads(Path('artifacts/octagon-audit.json').read_text(encoding='utf-8'));b=json.loads(Path('artifacts/octagon-baseline.json').read_text(encoding='utf-8'))
P=lambda p:f"{(p['x']-4800)*.5:.2f},{(2850-p['z'])*.5:.2f}"
colors={'industrial':'#dca958','office':'#a999dd','residential':'#8abca3','commercial':'#78aede','service':'#e0a0a7'}
svg='<svg viewBox="0 0 900 850" role="img" aria-label="正八角形八片区规划总览"><rect width="900" height="850" fill="#eef2e9"/>'
for c in b['water']['data']['cells']:
 if c['water']:
  x,y=map(float,P(c).split(','));svg+=f'<rect x="{x-20}" y="{y-20}" width="40" height="40" fill="#a9d3dd"/>'
for z in q['plan']['zones']:svg+=f'<polygon points="{" ".join(P(p) for p in z["polygon"])}" fill="{colors[z["kind"]]}" opacity=".65"/>'
for r in q['plan']['roads'][:48]:svg+=f'<polyline points="{" ".join(P(p) for p in r["points"])}" fill="none" stroke="#f8faf5" stroke-width="{r["width_m"]*.5}"/><polyline points="{" ".join(P(p) for p in r["points"])}" fill="none" stroke="#66766c" stroke-width="1"/>'
for i,z in enumerate(q['plan']['zones']):
 ang=(i+.5)*math.pi/4;x=400+285*math.cos(ang);y=410-285*math.sin(ang)
 svg+=f'<text x="{x}" y="{y}" text-anchor="middle" font-size="14" font-weight="700" fill="#22372d">{z["label"]}</text>'
svg+='<text x="400" y="414" text-anchor="middle" font-size="12">中央环岛</text><text x="40" y="50" font-size="14">世界 +Z ↑ · +X →</text><text x="400" y="815" text-anchor="middle" font-size="14">南侧既有铁路；外联走廊详见实时地图，跨线形式待原生预检</text></svg>'
rows=''.join(f'<tr><td>{z["label"]}</td><td>{["生产与物流集中外缘；内侧留非污染配套和缓冲用地","低密办公，作为工业与居住之间的空间过渡","住宅、小学与社区公园","住宅、诊所与步行服务","住宅、小学与社区公园","中学、警务；预留医疗扩容、福利与应急用地","低密商业与邮局；公交换乘预留","办公与消防；通往东侧物流外环"][i]}</td></tr>' for i,z in enumerate(q['plan']['zones']))
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>奥本山 · 八角城镇</title><style>*{box-sizing:border-box}body{margin:0;background:#f5f3ee;color:#20332c;font-family:system-ui,"Microsoft YaHei",sans-serif}header,main{max-width:1400px;margin:auto;padding:32px}header{border-bottom:1px solid #cdd8cc}h1{font-size:38px;margin:8px 0}p{line-height:1.75}.tag{color:#667c6f;font-size:13px;letter-spacing:2px}.layout{display:grid;grid-template-columns:1.3fr 1fr;gap:24px}.card{background:white;padding:24px;border:1px solid #d8dfd5;border-radius:14px}svg{width:100%;height:auto}table{border-collapse:collapse;width:100%;font-size:14px}td{border-bottom:1px solid #e0e6df;padding:12px 6px;line-height:1.6}td:first-child{width:36%;font-weight:600}.metrics{display:flex;gap:40px;margin:24px 0}.metrics b{display:block;font-size:25px}a{color:#216d57}iframe{width:100%;height:850px;border:1px solid #cbd5c7;border-radius:12px}li{line-height:1.8;margin:9px 0}.note{background:#fff0d8;padding:18px;border-radius:10px}@media(max-width:900px){.layout{display:block}.card{margin-bottom:20px}header,main{padding:18px}.metrics{gap:20px}}</style><header><div class="tag">AUBURN / OCTAGON TOWN / V1 · 规划，未施工</div><h1>一座八角形的城镇</h1><p>正八角外环、八条放射道路、八个功能片区。保留对称骨架，利用片区支路形成沿街开发空间。</p><div class="metrics"><div><b>1.31 km²</b>外环围合面积</div><div><b>520.45 m</b>八条等长外边</div><div><b>1,360 m</b>对角直径</div></div></header><main><div class="layout"><section class="card">'''+svg+'''</section><section class="card"><h2>八个片区</h2><table>'''+rows+'''</table><p>公共服务集中预留于⑥，同时小学、诊所、公园与消防分散到相关片区。工业边界的办公和绿地只作空间隔离，不能视为消除污染的保证。</p></section></div><section class="card" style="margin-top:24px"><h2>道路与公共服务</h2><ul><li>外环及八条放射主路暂选 24 米 Medium Road；内部同心支路选 16 米 Small Road。中央节点暂采用半径 80 米的小八角环岛，各条放射路轴线均指向几何中心。</li><li>内部支路位于半径 200、360、520 米处。扇区涂色表示用途预留，实际只沿合法道路格子分批划区，深处保留绿地或后续支路，不承诺涂色范围全部可成长。</li><li>11 处设施概念落位包含两所小学、一所中学、诊所、警务、两处消防、邮局、两处公园和自行车停放室。朝向与道路入口尚未绑定，须在道路落地后使用原生候选重新确定。</li><li>殡葬预留在公共服务片区外缘；垃圾与维护后勤预留在工业外缘。先核对既有服务的可达性与余量，再确定是否新建及具体资产。</li><li>水、电、污水必须有真实来源和连接：道路自带管网不代表已有供应。西侧保留清洁供水用地，东侧保留电力接入及污水处理空间；容量、污染及排放条件须专项确认。</li><li>两条南向/东向外联走廊为概念预留，跨铁路采用高架思路，桥面高度、坡长与高速立交端口待勘察预检。不得按图上的线交点直接连接高速或铁路。</li></ul></section><section class="card" style="margin-top:24px"><h2>勘察与施工条件</h2><p>中心世界坐标 X=5600、Z=2030，半径 680 米。主体 3,270 个土地采样点均位于已购范围，80 米水域采样未命中主体；主体地形网格约 533.57–542.86 米，八顶点约 533.51–543.06 米。采样不足以替代详细地形与碰撞检查。</p><p>当前风样本流向 +X、略偏 +Z，工业安排在东侧。该风样本只反映查询时刻，后续需按实际污染和风场复核。主体不穿越现有铁路和高速。</p><div class="note">地图校验的 11 项错误均为公共设施朝向尚未绑定（BUILDING_ROTATION_UNRESOLVED），不是已通过施工预检的建筑。尚未进行原生施工预检，未建设、拆除或平整地形。外联、生命线、设施最终朝向和造价仍待确认。先完成外联与管网设计，再按道路骨架 → 服务精确绑定 → 小批分区推进；本方案未指定人口上限。</div></section><h2 id="map">全地图实时底图与精确方案</h2><p>可缩放、拖动、切换图层并点击对象。<a href="auburn-octagon-map.html" target="_blank">单独打开地图</a> · <a href="../plans/auburn-octagon-town.json">结构化坐标方案（本地文件另附）</a></p><iframe title="实时地图上的八角城镇" src="auburn-octagon-map.html"></iframe></main></html>'''
# Relative plans link is not served by artifacts server; replace with a downloadable copy.
Path('artifacts/auburn-octagon-plan.json').write_text(json.dumps(q,ensure_ascii=False,indent=2),encoding='utf-8');page=page.replace('../plans/auburn-octagon-town.json','auburn-octagon-plan.json')
Path('artifacts/auburn-octagon-town.html').write_text(page,encoding='utf-8')
print('Overview page created')
