import json,math
from pathlib import Path
r=Path('artifacts');b=json.loads((r/'airport-relocation-baseline.json').read_text(encoding='utf-8'));a=json.loads((r/'airport-relocation-airspace.json').read_text(encoding='utf-8'));terrain=json.loads((r/'airport-relocation-site-terrain.json').read_text(encoding='utf-8'));box={'min_x':1132,'max_x':2268,'min_z':-1988,'max_z':-1612};tiles=b['tiles']['items']
def owned(x,z):return any(t['bounds']['min_x']<=x<=t['bounds']['max_x'] and t['bounds']['min_z']<=z<=t['bounds']['max_z'] for t in tiles)
assert all(owned(p['x'],p['z']) for p in a['samples'])
area=sum(max(0,min(t['bounds']['max_x'],2268)-max(t['bounds']['min_x'],1132))*max(0,min(t['bounds']['max_z'],-1612)-max(t['bounds']['min_z'],-1988)) for t in tiles);assert abs(area-1136*376)<1
def distance(v):p=v['position'];h=max(v['size_m'].values())/2;return math.hypot(max(abs(p['x']-1700)-568-h,0),max(abs(p['z']+1800)-188-h,0))
dh=min(distance(v) for v in b['snapshot']['buildings'] if v['kind']=='residential');hh=[p['height_m'] for p in terrain['items']]
plan={'version':2,'status':'conceptual_only','center':{'x':1700,'z':-1800},'bounds':box,'prefab':'Airport01','rotation_degrees':None,'rotation_source':'unresolved','orientation_intent':'east_west_runway_terminal_north','provisional_grade_m':544,'residential_clearance_m':dh,'terrain_range':[min(hh),max(hh)],'airspace':a,'owned_footprint_m2':area,'owned_airspace_samples':246,'road_concept':[{'x':1200,'z':-1600},{'x':2300,'z':-1600},{'x':2500,'z':-1680},{'x':2500,'z':-1280}],'highway_interchange_concept':{'x':2500,'z':-1480,'type':'grade_separated_four_ramps','native_preview':False},'old_site':'airport rejected; prior roads and grading retained; no demolition','native_preview':False}
(r/'auburn-airport-relocation-plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2),encoding='utf-8')
svg=['<svg id="map" viewBox="-600 -200 4200 3200" role="img" aria-label="东西向机场及两端净空规划"><rect x="-8000" y="-8000" width="16000" height="16000" fill="#e9edf1"/>']
for t in tiles:
 q=t['bounds'];svg.append(f'<rect x="{q["min_x"]}" y="{-q["max_z"]}" width="{q["max_x"]-q["min_x"]}" height="{q["max_z"]-q["min_z"]}" fill="#edf2e7" stroke="#c8d4c1" stroke-width="5"/>')
svg.append('<rect x="132" y="612" width="3136" height="2376" rx="1000" fill="#dcb55d" fill-opacity=".1" stroke="#bf9842" stroke-width="6" stroke-dasharray="25 14"/>')
for layer,color in [('roads','#627d87'),('tracks','#80654f')]:
 for v in b['snapshot'][layer]:
  c=v['curve'];svg.append(f'<path d="M{c["a"]["x"]},{-c["a"]["z"]} C{c["b"]["x"]},{-c["b"]["z"]} {c["c"]["x"]},{-c["c"]["z"]} {c["d"]["x"]},{-c["d"]["z"]}" fill="none" stroke="{color}" stroke-width="{v.get("width_m",6)}"/>')
for v in b['snapshot']['buildings']:
 p=v['position'];svg.append(f'<circle cx="{p["x"]}" cy="{-p["z"]}" r="12" fill="{"#408c61" if v["kind"]=="residential" else "#a2acad"}"/>')
svg.append('<rect x="1132" y="1612" width="1136" height="376" fill="#76b8c8" stroke="#166478" stroke-width="8"/><text x="1700" y="1800" text-anchor="middle" font-size="42">机场 · 跑道东西向</text>')
for c in a['curves']:svg.append(f'<path d="M{c["a"]["x"]},{-c["a"]["z"]} C{c["b"]["x"]},{-c["b"]["z"]} {c["c"]["x"]},{-c["c"]["z"]} {c["d"]["x"]},{-c["d"]["z"]}" fill="none" stroke="#d45360" stroke-width="75" opacity=".7"/>')
svg.append('<polyline points="1200,1600 2300,1600 2500,1680 2500,1280" stroke="#d47832" stroke-width="24" stroke-dasharray="30 12" fill="none"/><circle cx="2500" cy="1480" r="140" stroke="#d47832" stroke-width="6" stroke-dasharray="20 12" fill="none"/>')
for x,y,t in [(2500,1210,'新建立交预留'),(1700,1510,'航站楼前路'),(2800,2090,'东端净空'),(400,2090,'西端净空'),(400,300,'旧城住宅'),(6200,-2700,'八角城镇'),(6800,-1900,'原机场场址：停用规划')]:svg.append(f'<text x="{x}" y="{y}" font-size="42" fill="#203d46" stroke="#f5f7f0" stroke-width="8" paint-order="stroke">{t}</text>')
svg.append('</svg>')
page=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>奥本山 · 机场重新选址 V2</title><style>body{{margin:0;background:#eef2ed;color:#203e47;font:16px/1.7 system-ui}}main{{max-width:1200px;margin:auto;padding:32px}}section{{background:white;padding:24px;margin:24px 0;border-radius:14px}}h1{{font-size:36px}}svg{{width:100%;max-height:900px}}button{{padding:10px;margin:5px}}td,th{{padding:10px;border-bottom:1px solid #ddd;text-align:left}}table{{width:100%;border-collapse:collapse}}a{{color:#126c82}}.note{{color:#66797d}}</style><main><small>奥本山 / 机场重新选址 V2 / 仅规划</small><h1>机场移至旧城东南、高速南侧</h1><p>推荐中心 <b>X=1700，Z=-1800</b>，跑道改为东西向，航站楼朝北。机场边界距当前最近住宅约 <b>{dh/1000:.2f} 公里</b>，比原址约 1.02 公里更远。</p><section><h2>机场、净空与公路连接</h2><button onclick="document.querySelector('#map').setAttribute('viewBox','-600 -200 4200 3200')">新机场与旧城</button><button onclick="document.querySelector('#map').setAttribute('viewBox','-3500 -3500 11000 8000')">已购区域及原址</button>{''.join(svg)}<p class="note">蓝框：机场主体；红色：原生两端空域投影，各约 1 km × 75 m；黄线：1 km 敏感用地预留缓冲；橙线与虚线圆：新建道路和立交走廊，尚非精确匝道几何。浅绿方格为已购土地，绿色点为现有住宅。</p></section><section><h2>实测与约束</h2><table><tr><td>主体</td><td>Airport01，1136 × 376 米；X=1132–2268，Z=-1988–-1612，整个矩形在已购土地内</td></tr><tr><td>完整净空</td><td>东西总跨度约 2986 米；两端总宽各75米，末端比跑道高200米。246 个中心/边界采样点均在已购土地内</td></tr><tr><td>水域</td><td>32米网格，432个样本未命中水域；仍需细化岸线和原生整地检查</td></tr><tr><td>地形</td><td>45点采样 {min(hh):.1f}–{max(hh):.1f} 米；暂按544米场坪评估，最大样本填高约 {544-min(hh):.1f} 米、削低约 {max(0,max(hh)-544):.1f} 米</td></tr><tr><td>净空地形检查</td><td>两端各沿长度取41站，每站取中心与两侧，共246点。按544米场坪均未穿地，最小采样高差 {min(s['gap'] for s in a['samples']):.1f} 米。这不是安全余量承诺或原生碰撞通过证明</td></tr><tr><td>接公路</td><td>机场北侧建设专用站前路，向东北接新建高速立交（约2500,-1480），采用跨高速桥与四条匝道；不以平交口直接连接高速，不让接驳车流穿住宅区</td></tr></table></section><section><h2>噪音与施工边界</h2><p>继续保留机场边界外1公里不新增住宅、学校、医院的规划缓冲。起降净空决定能否放置和运行，噪音缓冲决定敏感用地距离；两者分别验收。距住宅更远可以降低风险，不能保证零噪音；投运后须检查住宅和学校噪音。</p><p>机场费75万，道路、立交、整地及水电污水接入另计。本站远离八角城镇现有市政管网，必须独立设计供给，不能假设高速承载水电污水。</p><p><b>本轮没有施工。</b>先完成新址原生机场/完整空域预检与立交方案再建。新道路尚未落地，因此机场准确旋转、入口绑定和跑道完整碰撞结果仍未确定。原址已建道路与整地保留，机场本体未建，不自动拆除。</p><a href="auburn-airport-relocation-plan.json">新址坐标与完整采样</a> · <a href="auburn-airport-plan-v1.html">原址及施工受阻记录</a></section></main></html>'''
old=r/'auburn-airport-plan.html'
if not (r/'auburn-airport-plan-v1.html').exists():(r/'auburn-airport-plan-v1.html').write_text(old.read_text(encoding='utf-8'),encoding='utf-8')
old.write_text(page,encoding='utf-8');print({'residential_m':dh,'terrain':[min(hh),max(hh)],'owned_m2':area})
