using System;
using System.Collections.Generic;
using System.Linq;
using Colossal.Mathematics;
using Game.Buildings;
using Game.Common;
using Game.Net;
using Game.Prefabs;
using Game.Simulation;
using Game.Tools;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;

namespace CityWeaver
{
    public sealed partial class GameQueryService
    {
        private readonly HashSet<string> m_TransportFacilityOperationIds = new HashSet<string>();
        private static bool IsTransportFacilityPrefab(EntityManager em, Entity prefab) => em.Exists(prefab) &&
            (em.HasComponent<TransportStationData>(prefab) || em.HasComponent<TransportDepotData>(prefab) ||
             em.HasComponent<PublicTransportStationData>(prefab) || em.HasComponent<CargoTransportStationData>(prefab));
        private static bool IsPlaceableTransportFacilityPrefab(EntityManager em, Entity prefab) => IsTransportFacilityPrefab(em, prefab) &&
            em.HasComponent<BuildingData>(prefab) && em.HasComponent<PlaceableObjectData>(prefab) && !em.HasComponent<Game.Prefabs.ServiceUpgradeData>(prefab);

        private Entity ResolveTransportFacilityPrefab(string wanted, World world)
        {
            var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();
            using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<PrefabData>()))using(var es=q.ToEntityArray(Allocator.Temp))
                foreach(var e in es)if(IsPlaceableTransportFacilityPrefab(em,e)&&ps.TryGetPrefab<PrefabBase>(e,out var p)&&string.Equals(p.name,wanted,StringComparison.OrdinalIgnoreCase))return e;
            throw new QueryException("TRANSPORT_FACILITY_PREFAB_NOT_FOUND","Use an exact name from list_transport_facility_prefabs.");
        }

        private void CollectFacilityNetworks(EntityManager em,Entity prefab,HashSet<Entity> seen,HashSet<string> transports,HashSet<string> tracks)
        {
            if(prefab==Entity.Null||!em.Exists(prefab)||!seen.Add(prefab))return;
            if(em.HasComponent<TransportStopData>(prefab))transports.Add(em.GetComponentData<TransportStopData>(prefab).m_TransportType.ToString());
            if(em.HasComponent<TransportDepotData>(prefab))transports.Add(em.GetComponentData<TransportDepotData>(prefab).m_TransportType.ToString());
            if(em.HasComponent<TrackData>(prefab))tracks.Add(em.GetComponentData<TrackData>(prefab).m_TrackType.ToString());
            if(em.HasBuffer<Game.Prefabs.SubObject>(prefab)){var b=em.GetBuffer<Game.Prefabs.SubObject>(prefab,true);for(int i=0;i<b.Length;i++)CollectFacilityNetworks(em,b[i].m_Prefab,seen,transports,tracks);}
            if(em.HasBuffer<Game.Prefabs.SubNet>(prefab)){var b=em.GetBuffer<Game.Prefabs.SubNet>(prefab,true);for(int i=0;i<b.Length;i++)CollectFacilityNetworks(em,b[i].m_Prefab,seen,transports,tracks);}
        }

        private JObject FacilityPrefabRow(World world,Entity e)
        {
            var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();ps.TryGetPrefab<PrefabBase>(e,out var p);
            var transports=new HashSet<string>();var tracks=new HashSet<string>();CollectFacilityNetworks(em,e,new HashSet<Entity>(),transports,tracks);
            var row=new JObject{{"name",p?.name},{"locked",RoadOperation.IsLocked(em,e)},{"station",em.HasComponent<TransportStationData>(e)},{"depot",em.HasComponent<TransportDepotData>(e)},
                {"passenger",em.HasComponent<PublicTransportStationData>(e)},{"cargo",em.HasComponent<CargoTransportStationData>(e)},{"transport_types",new JArray(transports.OrderBy(x=>x))},{"track_types",new JArray(tracks.OrderBy(x=>x))}};
            if(em.HasComponent<TransportStationData>(e)){var d=em.GetComponentData<TransportStationData>(e);row["comfort_factor"]=d.m_ComfortFactor;row["loading_factor"]=d.m_LoadingFactor;}
            if(em.HasComponent<TransportDepotData>(e)){var d=em.GetComponentData<TransportDepotData>(e);row["depot_transport_type"]=d.m_TransportType.ToString();row["vehicle_capacity"]=d.m_VehicleCapacity;row["energy_types"]=d.m_EnergyTypes.ToString();row["dispatch_center"]=d.m_DispatchCenter;row["size_class"]=d.m_SizeClass.ToString();}
            if(em.HasComponent<PlaceableObjectData>(e)){var d=em.GetComponentData<PlaceableObjectData>(e);row["construction_cost"]=d.m_ConstructionCost;row["placement_flags"]=d.m_Flags.ToString();row["placement_mode"]=(d.m_Flags&Game.Objects.PlacementFlags.RoadEdge)!=0?"road_edge":(d.m_Flags&Game.Objects.PlacementFlags.Shoreline)!=0?"shoreline":(d.m_Flags&Game.Objects.PlacementFlags.Floating)!=0?"floating":"roadside";}
            if(em.HasComponent<BuildingData>(e)){var d=em.GetComponentData<BuildingData>(e);row["lot_cells"]=new JObject{{"width",d.m_LotSize.x},{"depth",d.m_LotSize.y}};row["requires_road"]=(d.m_Flags&Game.Prefabs.BuildingFlags.RequireRoad)!=0;row["requires_access"]=(d.m_Flags&Game.Prefabs.BuildingFlags.RequireAccess)!=0;}
            if(em.HasComponent<ObjectGeometryData>(e)){var d=em.GetComponentData<ObjectGeometryData>(e);row["size_m"]=new JObject{{"x",d.m_Size.x},{"y",d.m_Size.y},{"z",d.m_Size.z}};}
            return row;
        }

        private JObject ListTransportFacilityPrefabs(JObject args,World world)
        {
            string search=((string)args["search"]??"").Trim(),kind=((string)args["kind"]??"all").ToLowerInvariant();if(!new[]{"all","station","depot","passenger","cargo"}.Contains(kind))throw new QueryException("INVALID_ARGUMENT","kind must be all, station, depot, passenger, or cargo.");
            bool unlocked=(bool?)args["unlocked_only"]??true;int offset=ComponentInspector.Int(args,"offset",0,0,10000),limit=ComponentInspector.Int(args,"limit",50,1,100);var rows=new List<JObject>();var em=world.EntityManager;
            using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<PrefabData>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var e in es)
            {
                if(!IsPlaceableTransportFacilityPrefab(em,e))continue;var row=FacilityPrefabRow(world,e);if(unlocked&&(bool)row["locked"]||search.Length>0&&((string)row["name"]??"").IndexOf(search,StringComparison.OrdinalIgnoreCase)<0)continue;
                if(kind=="station"&&!(bool)row["station"]||kind=="depot"&&!(bool)row["depot"]||kind=="passenger"&&!(bool)row["passenger"]||kind=="cargo"&&!(bool)row["cargo"])continue;rows.Add(row);
            }
            rows=rows.OrderBy(x=>(string)x["name"]).ToList();return new JObject{{"total",rows.Count},{"offset",offset},{"next_offset",offset+limit<rows.Count?new JValue(offset+limit):null},{"items",new JArray(rows.Skip(offset).Take(limit))}};
        }

        private Entity ResolveTransportFacility(JObject args,World world)
        {
            var e=ParseEntity((string)args["facility_id"],world.EntityManager);var em=world.EntityManager;if(!em.Exists(e)||!em.HasComponent<Building>(e)||!em.HasComponent<PrefabRef>(e)||em.HasComponent<Deleted>(e)||em.HasComponent<Temp>(e)||!IsTransportFacilityPrefab(em,em.GetComponentData<PrefabRef>(e).m_Prefab))throw new QueryException("TRANSPORT_FACILITY_NOT_FOUND","facility_id must identify a permanent transport station or depot.");return e;
        }
        private bool OwnedBy(EntityManager em,Entity child,Entity root){var at=child;for(int i=0;i<12&&em.Exists(at)&&em.HasComponent<Owner>(at);i++){at=em.GetComponentData<Owner>(at).m_Owner;if(at==root)return true;}return false;}
        private JObject FacilityRow(World world,Entity e,bool detail)
        {
            var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();var prefab=em.GetComponentData<PrefabRef>(e).m_Prefab;ps.TryGetPrefab<PrefabBase>(prefab,out var pf);var tr=em.GetComponentData<Game.Objects.Transform>(e);var building=em.GetComponentData<Building>(e);var row=new JObject{{"facility_id",m_Session+":"+e.Index+":"+e.Version},{"name",Name(world,e)},{"prefab",pf?.name},{"position",PointJson(tr.m_Position)},{"road_edge_id",OptionalEntity(m_Session,building.m_RoadEdge)},{"active",!BuildingUtils.CheckOption(building,BuildingOption.Inactive)},{"station",em.HasComponent<Game.Buildings.TransportStation>(e)},{"depot",em.HasComponent<Game.Buildings.TransportDepot>(e)},{"passenger",em.HasComponent<PublicTransportStation>(e)},{"cargo",em.HasComponent<Game.Buildings.CargoTransportStation>(e)}};
            if(em.HasComponent<Game.Buildings.TransportStation>(e)){var d=em.GetComponentData<Game.Buildings.TransportStation>(e);row["station_flags"]=d.m_Flags.ToString();row["stops_active"]=(d.m_Flags&TransportStationFlags.TransportStopsActive)!=0;row["comfort_factor"]=d.m_ComfortFactor;row["loading_factor"]=d.m_LoadingFactor;}
            if(em.HasComponent<Game.Buildings.TransportDepot>(e)){var d=em.GetComponentData<Game.Buildings.TransportDepot>(e);row["depot_flags"]=d.m_Flags.ToString();row["available_vehicles"]=d.m_AvailableVehicles;row["maintenance_requirement"]=d.m_MaintenanceRequirement;row["request_pending"]=d.m_TargetRequest!=Entity.Null;}
            if(em.HasComponent<Game.Buildings.CargoTransportStation>(e))row["cargo_work_amount"]=em.GetComponentData<Game.Buildings.CargoTransportStation>(e).m_WorkAmount;
            if(em.HasBuffer<Game.Vehicles.OwnedVehicle>(e))row["owned_vehicle_count"]=em.GetBuffer<Game.Vehicles.OwnedVehicle>(e,true).Length;
            if(detail)
            {
                var stops=new JArray();using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<Game.Routes.TransportStop>(),ComponentType.ReadOnly<PrefabRef>(),ComponentType.Exclude<Deleted>(),ComponentType.Exclude<Temp>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var s in es)if(OwnedBy(em,s,e)){var sp=em.GetComponentData<PrefabRef>(s).m_Prefab;var sd=em.HasComponent<TransportStopData>(sp)?em.GetComponentData<TransportStopData>(sp):default(TransportStopData);ps.TryGetPrefab<PrefabBase>(sp,out var sf);stops.Add(new JObject{{"stop_id",m_Session+":"+s.Index+":"+s.Version},{"prefab",sf?.name},{"transport_type",sd.m_TransportType.ToString()},{"passenger",sd.m_PassengerTransport},{"cargo",sd.m_CargoTransport},{"connected_line_count",em.HasBuffer<Game.Routes.ConnectedRoute>(s)?em.GetBuffer<Game.Routes.ConnectedRoute>(s,true).Length:0}});}row["stops"]=stops;
                var tracks=new JArray();using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<Edge>(),ComponentType.ReadOnly<Curve>(),ComponentType.ReadOnly<PrefabRef>(),ComponentType.Exclude<Deleted>(),ComponentType.Exclude<Temp>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var edge in es){var ep=em.GetComponentData<PrefabRef>(edge).m_Prefab;if(em.HasComponent<TrackData>(ep)&&OwnedBy(em,edge,e)){var td=em.GetComponentData<TrackData>(ep);tracks.Add(new JObject{{"track_edge_id",m_Session+":"+edge.Index+":"+edge.Version},{"track_type",td.m_TrackType.ToString()},{"length_m",em.GetComponentData<Curve>(edge).m_Length}});}}row["owned_tracks"]=tracks;
            }
            return row;
        }
        private JObject ListTransportFacilities(JObject args,World world){var rows=new List<JObject>();var em=world.EntityManager;using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<Building>(),ComponentType.ReadOnly<PrefabRef>(),ComponentType.ReadOnly<Game.Objects.Transform>(),ComponentType.Exclude<Deleted>(),ComponentType.Exclude<Temp>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var e in es)if(IsTransportFacilityPrefab(em,em.GetComponentData<PrefabRef>(e).m_Prefab))rows.Add(FacilityRow(world,e,false));return new JObject{{"total",rows.Count},{"items",new JArray(rows)}};}
        private JObject GetTransportFacility(JObject args,World world)=>FacilityRow(world,ResolveTransportFacility(args,world),true);
        private void ValidateFacilityName(JObject args,World world){var p=ResolveTransportFacilityPrefab((string)args["building_prefab"],world);if(RoadOperation.IsLocked(world.EntityManager,p))throw new QueryException("TRANSPORT_FACILITY_LOCKED","The selected transport facility is locked.");}
        private void ValidateFacilityOperation(BuildingOperation op,World world){var em=world.EntityManager;if(IsTransportFacilityPrefab(em,op.OriginalPrefab)||IsTransportFacilityPrefab(em,op.Prefab))return;if(op.Target!=Entity.Null){var at=op.Target;for(int i=0;i<12&&em.Exists(at)&&em.HasComponent<Owner>(at);i++){at=em.GetComponentData<Owner>(at).m_Owner;if(em.Exists(at)&&em.HasComponent<PrefabRef>(at)&&IsTransportFacilityPrefab(em,em.GetComponentData<PrefabRef>(at).m_Prefab))return;}}throw new QueryException("NOT_A_TRANSPORT_FACILITY_OPERATION","The operation does not target a transport station, depot, or one of its installed upgrades.");}
        private JObject PlanTransportFacilitySite(JObject args,World world){ValidateFacilityName(args,world);var p=ResolveTransportFacilityPrefab((string)args["building_prefab"],world);var f=world.EntityManager.GetComponentData<PlaceableObjectData>(p).m_Flags;return (f&(Game.Objects.PlacementFlags.Shoreline|Game.Objects.PlacementFlags.Floating|Game.Objects.PlacementFlags.RoadEdge|Game.Objects.PlacementFlags.RoadNode))!=0?PlanSpecialBuildingSite(args,world):PlanBuildingSite(args,world);}
        private JObject PreviewTransportFacility(JObject args,World world,string type){if(type=="place")ValidateFacilityName(args,world);else ResolveTransportFacility(new JObject{{"facility_id",args["facility_id"]}},world);var copy=(JObject)args.DeepClone();if(copy["facility_id"]!=null){copy["building_id"]=copy["facility_id"];copy.Remove("facility_id");}var op=PreviewBuildingOperation(copy,world,type);ValidateFacilityOperation(op,world);m_TransportFacilityOperationIds.Add(op.Id);return op.Json();}
        private BuildingOperation TransportFacilityOperation(JObject args){var op=BuildingOperationById(args);if(!m_TransportFacilityOperationIds.Contains(op.Id))throw new QueryException("TRANSPORT_FACILITY_OPERATION_NOT_FOUND","operation_id does not identify a transport-facility operation.");return op;}
        private JObject GetTransportFacilityOperation(JObject args,World world){return TransportFacilityOperation(args).Json();}
        private JObject ApplyTransportFacilityOperation(JObject args,World world){TransportFacilityOperation(args);return ApplyBuildingOperation(args,world);}
        private JObject CancelTransportFacilityOperation(JObject args,World world){TransportFacilityOperation(args);return CancelBuildingOperation(args);}
        private JObject FacilityBuildingArgs(JObject args,World world){ResolveTransportFacility(args,world);var copy=(JObject)args.DeepClone();copy["building_id"]=copy["facility_id"];copy.Remove("facility_id");return copy;}
        private JObject ListTransportFacilityUpgrades(JObject args,World world){return ListBuildingUpgrades(FacilityBuildingArgs(args,world),world);}
        private JObject SetTransportFacilityName(JObject args,World world){var result=SetBuildingName(FacilityBuildingArgs(args,world),world);result["facility_id"]=result["building_id"];result.Remove("building_id");return result;}
        private JObject SetTransportFacilityActive(JObject args,World world){var result=SetBuildingActive(FacilityBuildingArgs(args,world),world);result["facility_id"]=result["building_id"];result.Remove("building_id");return result;}
        private JObject ListTransportFacilityPolicies(JObject args,World world){return ListBuildingPolicies(FacilityBuildingArgs(args,world),world);}
        private JObject SetTransportFacilityPolicy(JObject args,World world){return SetBuildingPolicy(FacilityBuildingArgs(args,world),world);}
        private JObject PreviewTransportFacilityUpgrade(JObject args,World world){return PreviewTransportFacility(args,world,"upgrade");}
        private JObject PreviewTransportFacilityUpgradeRemoval(JObject args,World world)
        {
            var copy=(JObject)args.DeepClone();copy["building_id"]=copy["installed_upgrade_id"];copy.Remove("installed_upgrade_id");var op=PreviewBuildingOperation(copy,world,"remove_upgrade");ValidateFacilityOperation(op,world);m_TransportFacilityOperationIds.Add(op.Id);return op.Json();
        }

        private Entity[] TrackPrefabs(EntityManager em){using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<TrackData>(),ComponentType.ReadOnly<NetData>(),ComponentType.ReadOnly<NetGeometryData>(),ComponentType.ReadOnly<PlaceableNetData>(),ComponentType.ReadOnly<PrefabData>()))using(var es=q.ToEntityArray(Allocator.Temp))return es.ToArray();}
        private Entity ResolveTrackPrefab(string wanted,World world){var ps=world.GetExistingSystemManaged<PrefabSystem>();foreach(var e in TrackPrefabs(world.EntityManager))if(ps.TryGetPrefab<PrefabBase>(e,out var p)&&p is TrackPrefab&&string.Equals(p.name,wanted,StringComparison.OrdinalIgnoreCase))return e;throw new QueryException("TRACK_PREFAB_NOT_FOUND","Use an exact name from list_transport_track_prefabs.");}
        private JObject ListTransportTrackPrefabs(JObject args,World world)
        {
            string search=((string)args["search"]??"").Trim(),type=((string)args["track_type"]??"").Trim();bool unlocked=(bool?)args["unlocked_only"]??true;var rows=new List<JObject>();var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();
            foreach(var e in TrackPrefabs(em)){if(!ps.TryGetPrefab<PrefabBase>(e,out var p)||!(p is TrackPrefab)||search.Length>0&&p.name.IndexOf(search,StringComparison.OrdinalIgnoreCase)<0)continue;var td=em.GetComponentData<TrackData>(e);if(type.Length>0&&!string.Equals(type,td.m_TrackType.ToString(),StringComparison.OrdinalIgnoreCase))continue;bool locked=RoadOperation.IsLocked(em,e);if(unlocked&&locked)continue;var g=em.GetComponentData<NetGeometryData>(e);var place=em.GetComponentData<PlaceableNetData>(e);rows.Add(new JObject{{"name",p.name},{"track_type",td.m_TrackType.ToString()},{"speed_limit_mps",td.m_SpeedLimit},{"locked",locked},{"width_m",g.m_DefaultWidth},{"max_slope",g.m_MaxSlopeSteepness},{"edge_length_m",new JObject{{"min",g.m_EdgeLengthRange.min},{"max",g.m_EdgeLengthRange.max}}},{"elevation_range_m",new JObject{{"min",place.m_ElevationRange.min},{"max",place.m_ElevationRange.max}}},{"construction_cost_per_m",place.m_DefaultConstructionCost},{"placement_flags",place.m_PlacementFlags.ToString()}});}
            return new JObject{{"total",rows.Count},{"items",new JArray(rows.OrderBy(x=>(string)x["name"]))}};
        }
        private bool IsPermanentTrack(EntityManager em,Entity e)=>em.Exists(e)&&em.HasComponent<Edge>(e)&&em.HasComponent<Curve>(e)&&em.HasComponent<PrefabRef>(e)&&!em.HasComponent<Temp>(e)&&!em.HasComponent<Deleted>(e)&&em.HasComponent<TrackData>(em.GetComponentData<PrefabRef>(e).m_Prefab);
        private JObject TrackRow(World world,Entity e,bool detail){var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();var p=em.GetComponentData<PrefabRef>(e).m_Prefab;ps.TryGetPrefab<PrefabBase>(p,out var pf);var td=em.GetComponentData<TrackData>(p);var curve=em.GetComponentData<Curve>(e);var edge=em.GetComponentData<Edge>(e);var row=new JObject{{"track_edge_id",m_Session+":"+e.Index+":"+e.Version},{"prefab",pf?.name},{"track_type",td.m_TrackType.ToString()},{"speed_limit_mps",td.m_SpeedLimit},{"length_m",curve.m_Length},{"start",PointJson(curve.m_Bezier.a)},{"end",PointJson(curve.m_Bezier.d)},{"start_node_id",m_Session+":"+edge.m_Start.Index+":"+edge.m_Start.Version},{"end_node_id",m_Session+":"+edge.m_End.Index+":"+edge.m_End.Version}};if(detail){row["curve"]=new JObject{{"a",PointJson(curve.m_Bezier.a)},{"b",PointJson(curve.m_Bezier.b)},{"c",PointJson(curve.m_Bezier.c)},{"d",PointJson(curve.m_Bezier.d)}};if(em.HasComponent<Elevation>(e)){var x=em.GetComponentData<Elevation>(e).m_Elevation;row["elevation_m"]=new JObject{{"start",x.x},{"end",x.y}};}row["owned_by"]=em.HasComponent<Owner>(e)?m_Session+":"+em.GetComponentData<Owner>(e).m_Owner.Index+":"+em.GetComponentData<Owner>(e).m_Owner.Version:null;}return row;}
        private JObject ListTransportTracks(JObject args,World world){string type=((string)args["track_type"]??"").Trim();var rows=new List<JObject>();var em=world.EntityManager;using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<Edge>(),ComponentType.ReadOnly<Curve>(),ComponentType.ReadOnly<PrefabRef>(),ComponentType.Exclude<Deleted>(),ComponentType.Exclude<Temp>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var e in es)if(IsPermanentTrack(em,e)){var r=TrackRow(world,e,false);if(type.Length==0||string.Equals(type,(string)r["track_type"],StringComparison.OrdinalIgnoreCase))rows.Add(r);}return new JObject{{"total",rows.Count},{"items",new JArray(rows)}};}
        private JObject GetTransportTrack(JObject args,World world){var e=ParseEntity((string)args["track_edge_id"],world.EntityManager);if(!IsPermanentTrack(world.EntityManager,e))throw new QueryException("TRANSPORT_TRACK_NOT_FOUND","track_edge_id must identify a permanent train, subway, or tram track.");return TrackRow(world,e,true);}
        private RoadEndpoint TrackPoint(JObject value,World world,Game.Simulation.TerrainHeightData heights)
        {
            if(value==null)throw new QueryException("INVALID_ARGUMENT","Each point requires x and z.");var em=world.EntityManager;float elevation=BuildingNumber(value,"elevation_m",0,-50,200);var pos=new float3(BuildingNumber(value,"x",0,-7168,7168),0,BuildingNumber(value,"z",0,-7168,7168));Entity target=Entity.Null;float split=0;
            if(value["node_id"]!=null&&value["edge_id"]!=null)throw new QueryException("INVALID_ARGUMENT","Use node_id or edge_id, not both.");
            if(value["node_id"]!=null){target=ParseEntity((string)value["node_id"],em);if(!em.HasComponent<Node>(target)||em.HasComponent<Deleted>(target)||em.HasComponent<Temp>(target))throw new QueryException("INVALID_TRACK_NODE","node_id must identify a permanent network node.");bool track=false;if(em.HasBuffer<ConnectedEdge>(target)){var b=em.GetBuffer<ConnectedEdge>(target,true);for(int i=0;i<b.Length;i++)if(IsPermanentTrack(em,b[i].m_Edge)){track=true;break;}}if(!track)throw new QueryException("INVALID_TRACK_NODE","node_id is not connected to a transport track.");pos=em.GetComponentData<Node>(target).m_Position;}
            else if(value["edge_id"]!=null){target=ParseEntity((string)value["edge_id"],em);if(!IsPermanentTrack(em,target))throw new QueryException("INVALID_TRACK_EDGE","edge_id must identify a permanent transport track.");var c=em.GetComponentData<Curve>(target).m_Bezier;MathUtils.Distance(c.xz,pos.xz,out split);pos=MathUtils.Position(c,split);if(math.distance(pos.xz,new float2(BuildingNumber(value,"x",0,-7168,7168),BuildingNumber(value,"z",0,-7168,7168)))>8)throw new QueryException("INVALID_TRACK_EDGE","The requested point must be within 8 metres of edge_id.");}
            else pos.y=TerrainUtils.SampleHeight(ref heights,pos)+elevation;
            if(target!=Entity.Null&&math.abs(elevation)>.01f)throw new QueryException("INVALID_ENDPOINT","Attached track endpoints inherit their current elevation.");return new RoadEndpoint{Position=pos,Target=target,Split=split,Elevation=elevation};
        }
        private void ValidateTrackCurve(Bezier4x3 curve,float aElevation,float bElevation,Entity prefab,EntityManager em){var length=MathUtils.Length(curve);var g=em.GetComponentData<NetGeometryData>(prefab);var p=em.GetComponentData<PlaceableNetData>(prefab);float min=math.max(16,g.m_EdgeLengthRange.min),max=g.m_EdgeLengthRange.max>0?g.m_EdgeLengthRange.max:300;if(length<min||length>max)throw new QueryException("INVALID_TRACK_LENGTH","Each track segment must be within the selected prefab edge length range and at least 16 metres.");if(aElevation<p.m_ElevationRange.min||aElevation>p.m_ElevationRange.max||bElevation<p.m_ElevationRange.min||bElevation>p.m_ElevationRange.max)throw new QueryException("INVALID_ELEVATION","Track elevation is outside the prefab range.");float limit=g.m_MaxSlopeSteepness>0?g.m_MaxSlopeSteepness:.08f;var prev=curve.a;for(int i=1;i<=32;i++){var x=MathUtils.Position(curve,i/32f);if(math.abs(x.y-prev.y)/math.max(.01f,math.distance(x.xz,prev.xz))>limit)throw new QueryException("STEEP_SLOPE","Track exceeds the selected prefab slope limit.");prev=x;}}
        private JObject TrackOperationJson(RoadOperation op){var j=op.Json();j["track_prefab"]=op.PrefabName;j["created_track_ids"]=j["created_road_ids"]?.DeepClone()??new JArray();j["target_track_edge_ids"]=j["target_edge_ids"]?.DeepClone()??new JArray();j["note"]="A preview is temporary. Only completed confirms permanent transport-track edges.";return j;}
        private JObject PreviewTransportTrack(JObject args,World world)
        {
            string key=RequestKey(args),fingerprint=new JObject{{"kind","transport_track"},{"track_prefab",args["track_prefab"]?.DeepClone()},{"points",args["points"]?.DeepClone()}}.ToString(Formatting.None);if(m_RoadRequestIds.TryGetValue(key,out var oldId)){var old=m_RoadOperations[oldId];if(old.Fingerprint!=fingerprint)throw new QueryException("IDEMPOTENCY_CONFLICT","request_id already belongs to another operation.");if(old.TransactionKind!="transport_track")throw new QueryException("IDEMPOTENCY_CONFLICT","request_id belongs to a road operation.");return TrackOperationJson(old);}if(!(args["points"] is JArray points)||points.Count<2||points.Count>16)throw new QueryException("INVALID_ARGUMENT","points must contain 2..16 track points.");if(world.GetExistingSystemManaged<SimulationSystem>().selectedSpeed!=0)throw new QueryException("CITY_MUST_BE_PAUSED","Pause the city before previewing tracks.");var tool=RoadTool(world);if(tool.Busy||!(world.GetExistingSystemManaged<ToolSystem>().activeTool is DefaultToolSystem))throw new QueryException("TOOL_BUSY","Select the default tool and finish another preview.");var em=world.EntityManager;var prefab=ResolveTrackPrefab((string)args["track_prefab"],world);if(RoadOperation.IsLocked(em,prefab))throw new QueryException("TRACK_PREFAB_LOCKED","The selected track prefab is locked.");var heights=world.GetExistingSystemManaged<TerrainSystem>().GetHeightData(true);if(!heights.isCreated)throw new QueryException("TERRAIN_UNAVAILABLE","Terrain heights are unavailable.");var parsed=points.Select(x=>TrackPoint(x as JObject,world,heights)).ToList();var op=new RoadOperation{Session=m_Session,RequestId=key,Fingerprint=fingerprint,OperationType="create",TransactionKind="transport_track",Prefab=prefab,PrefabName=(string)args["track_prefab"],CurveMode="polyline"};for(int i=0;i+1<parsed.Count;i++){var a=parsed[i];var b=parsed[i+1];if(a.Target!=Entity.Null&&a.Target==b.Target&&math.abs(a.Split-b.Split)<.001f)throw new QueryException("INVALID_ENDPOINT","Adjacent points resolve to the same track position.");var c=NetUtils.StraightCurve(a.Position,b.Position);ValidateTrackCurve(c,a.Elevation,b.Elevation,prefab,em);op.Segments.Add(new RoadSegmentPlan{Start=a.Position,End=b.Position,StartTarget=a.Target,EndTarget=b.Target,StartSplit=a.Split,EndSplit=b.Split,StartElevation=a.Elevation,EndElevation=b.Elevation,Curve=c});}var first=op.Segments[0];var last=op.Segments[op.Segments.Count-1];op.Start=first.Start;op.End=last.End;op.StartNode=first.StartTarget;op.EndNode=last.EndTarget;op.StartSplit=first.StartSplit;op.EndSplit=last.EndSplit;op.StartElevation=first.StartElevation;op.EndElevation=last.EndElevation;op.Curve=first.Curve;tool.Begin(op);m_RoadOperations.Add(op.Id,op);m_RoadRequestIds.Add(key,op.Id);return TrackOperationJson(op);
        }
        private JObject PreviewTransportTrackDelete(JObject args,World world)
        {
            string key=RequestKey(args),fingerprint=new JObject{{"kind","transport_track_delete"},{"track_edge_ids",args["track_edge_ids"]?.DeepClone()}}.ToString(Formatting.None);if(m_RoadRequestIds.TryGetValue(key,out var oldId)){var old=m_RoadOperations[oldId];if(old.Fingerprint!=fingerprint||old.TransactionKind!="transport_track")throw new QueryException("IDEMPOTENCY_CONFLICT","request_id belongs to another operation.");return TrackOperationJson(old);}if(!(args["track_edge_ids"] is JArray ids)||ids.Count<1||ids.Count>64)throw new QueryException("INVALID_ARGUMENT","track_edge_ids must contain 1..64 tracks.");if(world.GetExistingSystemManaged<SimulationSystem>().selectedSpeed!=0)throw new QueryException("CITY_MUST_BE_PAUSED","Pause the city before deleting tracks.");var tool=RoadTool(world);if(tool.Busy||!(world.GetExistingSystemManaged<ToolSystem>().activeTool is DefaultToolSystem))throw new QueryException("TOOL_BUSY","Select the default tool and finish another preview.");var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();var op=new RoadOperation{Session=m_Session,RequestId=key,Fingerprint=fingerprint,OperationType="batch_demolish",TransactionKind="transport_track",CurveMode="existing"};var unique=new HashSet<Entity>();foreach(var token in ids){var e=ParseEntity((string)token,em);if(!unique.Add(e))throw new QueryException("DUPLICATE_TRACK_EDGE","track_edge_ids must be unique.");if(!IsPermanentTrack(em,e))throw new QueryException("TRANSPORT_TRACK_NOT_FOUND","Every ID must identify a permanent transport track.");var p=em.GetComponentData<PrefabRef>(e).m_Prefab;ps.TryGetPrefab<PrefabBase>(p,out var pf);var edge=em.GetComponentData<Edge>(e);var curve=em.GetComponentData<Curve>(e).m_Bezier;var elevation=em.HasComponent<Elevation>(e)?em.GetComponentData<Elevation>(e).m_Elevation:new float2(0);op.TargetEdges.Add(e);op.Segments.Add(new RoadSegmentPlan{TargetEdge=e,OriginalPrefab=p,OriginalPrefabName=pf?.name,Start=curve.a,End=curve.d,StartTarget=edge.m_Start,EndTarget=edge.m_End,StartElevation=elevation.x,EndElevation=elevation.y,Curve=curve});}var f=op.Segments[0];var l=op.Segments[op.Segments.Count-1];op.TargetEdge=op.TargetEdges[0];op.Prefab=f.OriginalPrefab;op.PrefabName=f.OriginalPrefabName;op.OriginalPrefabName=f.OriginalPrefabName;op.Start=f.Start;op.End=l.End;op.StartNode=f.StartTarget;op.EndNode=l.EndTarget;op.Curve=f.Curve;tool.Begin(op);m_RoadOperations.Add(op.Id,op);m_RoadRequestIds.Add(key,op.Id);return TrackOperationJson(op);
        }
        private RoadOperation TransportTrackOperation(JObject args){var op=RoadOperationById(args);if(op.TransactionKind!="transport_track")throw new QueryException("TRANSPORT_TRACK_OPERATION_NOT_FOUND","operation_id does not identify a track operation.");return op;}
        private JObject GetTransportTrackOperation(JObject args){return TrackOperationJson(TransportTrackOperation(args));}
        private JObject ApplyTransportTrackOperation(JObject args){TransportTrackOperation(args);return TrackOperationJsonAfter(CommitRoad(args));}
        private JObject TrackOperationJsonAfter(JObject ignored){var op=m_RoadOperations[(string)ignored["operation_id"]];return TrackOperationJson(op);}
        private JObject CancelTransportTrackOperation(JObject args){var op=TransportTrackOperation(args);CancelRoad(args);return TrackOperationJson(op);}
    }
}

