using System;
using System.Collections.Generic;
using System.Linq;
using Colossal.Entities;
using Game.Common;
using Game.Pathfind;
using Game.Prefabs;
using Game.Routes;
using Game.Simulation;
using Game.Tools;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;

namespace CityWeaver
{
    public sealed class TransportLineOperation
    {
        public string Id=Guid.NewGuid().ToString("N"),Session,RequestId,Fingerprint,Type,State="queued",Error,Name,PrefabName;
        public Entity Prefab,Target,Result; public Color32 Color;
        public readonly List<Entity> Stops=new List<Entity>(), OriginalStops=new List<Entity>();
        public bool CommitRequested,CancelRequested,ApplyDispatched,NameApplied;
        public DateTime Expires=DateTime.UtcNow.AddMinutes(5); public JArray Errors=new JArray(),Warnings=new JArray();
        public bool Terminal=>State=="completed"||State=="failed"||State=="cancelled"||State=="expired"||State=="outcome_unknown";
        public string EntityId(Entity e)=>e==Entity.Null?null:Session+":"+e.Index+":"+e.Version;
        public JObject Json()=>new JObject{{"operation_id",Id},{"session_id",Session},{"request_id",RequestId},{"state",State},{"operation_type",Type},{"line_prefab",PrefabName},{"target_line_id",EntityId(Target)},{"result_line_id",EntityId(Result)},{"name",Name},{"stop_count",Stops.Count},{"stop_ids",new JArray(Stops.Select(EntityId))},{"color",new JObject{{"r",Color.r},{"g",Color.g},{"b",Color.b},{"a",Color.a}}},{"errors",Errors},{"warnings",Warnings},{"error",Error},{"can_commit",State=="preview_ready"},{"expires_at_utc",Expires.ToString("O")}};
    }

    public sealed partial class GameQueryService
    {
        private readonly Dictionary<string,TransportLineOperation> m_TransportOperations=new Dictionary<string,TransportLineOperation>();
        private readonly Dictionary<string,string> m_TransportRequestIds=new Dictionary<string,string>();
        private void ResetTransportOperations(){m_TransportOperations.Clear();m_TransportRequestIds.Clear();}
        private static bool PermanentLine(EntityManager em,Entity e)=>em.Exists(e)&&em.HasComponent<TransportLine>(e)&&em.HasBuffer<RouteWaypoint>(e)&&!em.HasComponent<Temp>(e)&&!em.HasComponent<Deleted>(e);
        private Entity ResolveLine(JObject args,World world){var e=ParseEntity((string)args["line_id"],world.EntityManager);if(!PermanentLine(world.EntityManager,e))throw new QueryException("TRANSPORT_LINE_NOT_FOUND","line_id must identify a permanent transport line.");return e;}
        private Entity ResolveStopToken(string id,World world){var e=ParseEntity(id,world.EntityManager);var em=world.EntityManager;if(!em.Exists(e)||!em.HasComponent<Game.Routes.TransportStop>(e)||!em.HasBuffer<ConnectedRoute>(e)||em.HasComponent<Deleted>(e)||em.HasComponent<Temp>(e))throw new QueryException("TRANSPORT_STOP_NOT_FOUND","Every stop_id must identify a permanent transport stop.");return e;}
        private float3 StopPosition(EntityManager em,Entity e){if(em.HasComponent<Game.Objects.Transform>(e))return em.GetComponentData<Game.Objects.Transform>(e).m_Position;if(em.HasComponent<Position>(e))return em.GetComponentData<Position>(e).m_Position;throw new QueryException("TRANSPORT_STOP_POSITION_UNAVAILABLE","A selected stop has no readable world position.");}
        private List<Entity> LineStops(EntityManager em,Entity line){var r=new List<Entity>();var b=em.GetBuffer<RouteWaypoint>(line,true);for(int i=0;i<b.Length;i++){var w=b[i].m_Waypoint;r.Add(em.HasComponent<Connected>(w)?em.GetComponentData<Connected>(w).m_Connected:Entity.Null);}return r;}
        private string Name(World world,Entity e){string n=null;world.GetExistingSystemManaged<Game.UI.NameSystem>()?.TryGetCustomName(e,out n);return n;}
        private JObject ListTransportLinePrefabs(JObject args,World world)
        {
            var rows=new List<JObject>();var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();string search=(string)args["search"]??"";using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<PrefabData>(),ComponentType.ReadOnly<TransportLineData>(),ComponentType.ReadOnly<RouteData>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var e in es)if(ps.TryGetPrefab<PrefabBase>(e,out var p)&&p.name.IndexOf(search,StringComparison.OrdinalIgnoreCase)>=0){var d=em.GetComponentData<TransportLineData>(e);var rd=em.GetComponentData<RouteData>(e);rows.Add(new JObject{{"name",p.name},{"transport_type",d.m_TransportType.ToString()},{"passenger",d.m_PassengerTransport},{"cargo",d.m_CargoTransport},{"size_class",d.m_SizeClass.ToString()},{"default_vehicle_interval",d.m_DefaultVehicleInterval},{"default_unbunching_factor",d.m_DefaultUnbunchingFactor},{"stop_duration",d.m_StopDuration},{"min_stop_spacing_m",rd.m_SnapDistance},{"locked",RoadOperation.IsLocked(em,e)}});}return new JObject{{"total",rows.Count},{"items",new JArray(rows.OrderBy(x=>(string)x["name"]))}};
        }
        private JObject ListTransportStops(JObject args,World world)
        {
            var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();string type=((string)args["transport_type"]??"").Trim();bool passengerOnly=args["passenger_only"]!=null&&(bool)args["passenger_only"],cargoOnly=args["cargo_only"]!=null&&(bool)args["cargo_only"];var rows=new List<JObject>();using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<Game.Routes.TransportStop>(),ComponentType.ReadOnly<PrefabRef>(),ComponentType.ReadOnly<ConnectedRoute>(),ComponentType.Exclude<Temp>(),ComponentType.Exclude<Deleted>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var e in es){var prefab=em.GetComponentData<PrefabRef>(e).m_Prefab;if(!em.HasComponent<TransportStopData>(prefab))continue;var d=em.GetComponentData<TransportStopData>(prefab);if(type.Length>0&&!string.Equals(type,d.m_TransportType.ToString(),StringComparison.OrdinalIgnoreCase)||passengerOnly&&!d.m_PassengerTransport||cargoOnly&&!d.m_CargoTransport)continue;var pos=StopPosition(em,e);ps.TryGetPrefab<PrefabBase>(prefab,out var pf);var cr=em.GetBuffer<ConnectedRoute>(e,true);rows.Add(new JObject{{"stop_id",m_Session+":"+e.Index+":"+e.Version},{"name",Name(world,e)},{"prefab",pf?.name},{"transport_type",d.m_TransportType.ToString()},{"passenger",d.m_PassengerTransport},{"cargo",d.m_CargoTransport},{"position",PointJson(pos)},{"connected_line_count",cr.Length},{"outside_connection",em.HasComponent<Game.Objects.OutsideConnection>(e)}});}return new JObject{{"total",rows.Count},{"items",new JArray(rows)}};
        }
        private JObject LineRow(World world,Entity e,bool detail)
        {
            var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();var pr=em.GetComponentData<PrefabRef>(e);ps.TryGetPrefab<PrefabBase>(pr.m_Prefab,out var pf);var pd=em.GetComponentData<TransportLineData>(pr.m_Prefab);var line=em.GetComponentData<TransportLine>(e);var route=em.GetComponentData<Route>(e);var stops=LineStops(em,e);string schedule=RouteUtils.CheckOption(route,RouteOption.Day)?"day":RouteUtils.CheckOption(route,RouteOption.Night)?"night":"day_and_night";var row=new JObject{{"line_id",m_Session+":"+e.Index+":"+e.Version},{"name",Name(world,e)},{"prefab",pf?.name},{"transport_type",pd.m_TransportType.ToString()},{"passenger",pd.m_PassengerTransport},{"cargo",pd.m_CargoTransport},{"active",!RouteUtils.CheckOption(route,RouteOption.Inactive)},{"schedule",schedule},{"stop_count",stops.Count},{"vehicle_interval",line.m_VehicleInterval},{"unbunching_factor",line.m_UnbunchingFactor},{"ticket_price",line.m_TicketPrice},{"flags",line.m_Flags.ToString()},{"complete",(route.m_Flags&RouteFlags.Complete)!=0}};
            if(em.HasComponent<RouteNumber>(e))row["route_number"]=em.GetComponentData<RouteNumber>(e).m_Number;if(em.HasComponent<Game.Routes.Color>(e)){var c=em.GetComponentData<Game.Routes.Color>(e).m_Color;row["color"]=new JObject{{"r",c.r},{"g",c.g},{"b",c.b},{"a",c.a}};}if(em.HasBuffer<RouteVehicle>(e))row["vehicle_count"]=em.GetBuffer<RouteVehicle>(e,true).Length;
            if(detail)
            {
                var items=new JArray();var wb=em.GetBuffer<RouteWaypoint>(e,true);int totalWaiting=0;
                for(int i=0;i<wb.Length;i++)
                {
                    var w=wb[i].m_Waypoint;var s=stops[i];var item=new JObject{{"index",i},{"waypoint_id",m_Session+":"+w.Index+":"+w.Version},{"stop_id",s==Entity.Null?null:m_Session+":"+s.Index+":"+s.Version}};
                    if(em.HasComponent<Position>(w))item["position"]=PointJson(em.GetComponentData<Position>(w).m_Position);
                    if(em.HasComponent<WaitingPassengers>(w)){var wait=em.GetComponentData<WaitingPassengers>(w);item["waiting_passengers"]=wait.m_Count;item["average_waiting_time"]=wait.m_AverageWaitingTime;item["ongoing_wait_accumulation"]=wait.m_OngoingAccumulation;item["concluded_wait_accumulation"]=wait.m_ConcludedAccumulation;totalWaiting+=wait.m_Count;}
                    items.Add(item);
                }
                row["stops"]=items;row["total_waiting_passengers"]=totalWaiting;
                if(em.HasBuffer<RouteSegment>(e)){float distance=0;var sb=em.GetBuffer<RouteSegment>(e,true);for(int i=0;i<sb.Length;i++){var s=sb[i].m_Segment;if(em.HasComponent<PathInformation>(s))distance+=em.GetComponentData<PathInformation>(s).m_Distance;}row["route_distance_m"]=distance;}
                var vehicles=new JArray();
                if(em.HasBuffer<RouteVehicle>(e))
                {
                    var vb=em.GetBuffer<RouteVehicle>(e,true);
                    for(int i=0;i<vb.Length;i++)
                    {
                        var v=vb[i].m_Vehicle;if(!em.Exists(v)||em.HasComponent<Deleted>(v))continue;var item=new JObject{{"vehicle_id",m_Session+":"+v.Index+":"+v.Version}};
                        if(em.HasComponent<PrefabRef>(v)){var vp=em.GetComponentData<PrefabRef>(v).m_Prefab;if(ps.TryGetPrefab<PrefabBase>(vp,out var vpf))item["prefab"]=vpf.name;if(em.HasComponent<PublicTransportVehicleData>(vp))item["passenger_capacity"]=em.GetComponentData<PublicTransportVehicleData>(vp).m_PassengerCapacity;if(em.HasComponent<CargoTransportVehicleData>(vp))item["cargo_capacity"]=em.GetComponentData<CargoTransportVehicleData>(vp).m_CargoCapacity;}
                        if(em.HasComponent<Game.Objects.Transform>(v))item["position"]=PointJson(em.GetComponentData<Game.Objects.Transform>(v).m_Position);
                        if(em.HasComponent<Game.Vehicles.PublicTransport>(v)){var pt=em.GetComponentData<Game.Vehicles.PublicTransport>(v);item["state"]=pt.m_State.ToString();item["departure_frame"]=pt.m_DepartureFrame;item["request_count"]=pt.m_RequestCount;}
                        if(em.HasBuffer<Game.Vehicles.Passenger>(v))item["passenger_count"]=em.GetBuffer<Game.Vehicles.Passenger>(v,true).Length;
                        vehicles.Add(item);
                    }
                }
                row["vehicles"]=vehicles;row["vehicle_request_pending"]=line.m_VehicleRequest!=Entity.Null;
                row["policies"]=new JArray(ReadRoutePolicies(world,e));
            }
            return row;
        }
        private JObject ListTransportLines(JObject args,World world){var rows=new List<JObject>();using(var q=world.EntityManager.CreateEntityQuery(ComponentType.ReadOnly<TransportLine>(),ComponentType.ReadOnly<RouteWaypoint>(),ComponentType.Exclude<Temp>(),ComponentType.Exclude<Deleted>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var e in es)rows.Add(LineRow(world,e,false));return new JObject{{"total",rows.Count},{"items",new JArray(rows)}};}
        private JObject GetTransportLine(JObject args,World world)=>LineRow(world,ResolveLine(args,world),true);
        private Entity ResolveLinePrefab(string wanted,World world)
        {
            var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<PrefabData>(),ComponentType.ReadOnly<TransportLineData>(),ComponentType.ReadOnly<RouteData>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var e in es)if(ps.TryGetPrefab<PrefabBase>(e,out var p)&&string.Equals(p.name,wanted,StringComparison.OrdinalIgnoreCase)){if(RoadOperation.IsLocked(em,e))throw new QueryException("TRANSPORT_LINE_PREFAB_LOCKED","The selected line prefab is locked.");return e;}throw new QueryException("TRANSPORT_LINE_PREFAB_NOT_FOUND","Use an exact unlocked name from list_transport_line_prefabs.");
        }
        private List<Entity> ParseStops(JArray ids,Entity prefab,World world)
        {
            if(ids==null||ids.Count<2||ids.Count>64)throw new QueryException("INVALID_ARGUMENT","stop_ids must contain 2..64 stops.");var em=world.EntityManager;var pd=em.GetComponentData<TransportLineData>(prefab);var result=new List<Entity>();foreach(var t in ids){var s=ResolveStopToken((string)t,world);if(result.Contains(s))throw new QueryException("DUPLICATE_TRANSPORT_STOP","A line may contain each stop once.");var sp=em.GetComponentData<PrefabRef>(s).m_Prefab;if(!em.HasComponent<TransportStopData>(sp))throw new QueryException("INCOMPATIBLE_TRANSPORT_STOP","The selected stop has no transport type data.");var sd=em.GetComponentData<TransportStopData>(sp);if(sd.m_TransportType!=pd.m_TransportType||pd.m_PassengerTransport&&!sd.m_PassengerTransport||pd.m_CargoTransport&&!sd.m_CargoTransport)throw new QueryException("INCOMPATIBLE_TRANSPORT_STOP","Every stop must match the line transport and passenger/cargo type.");result.Add(s);}return result;
        }
        private TransportLineOperation PreviewTransportLine(JObject args,World world,string type)
        {
            string key=RequestKey(args),fp=type+":"+args.ToString(Formatting.None);if(m_TransportRequestIds.TryGetValue(key,out var oid)){var old=m_TransportOperations[oid];if(old.Fingerprint!=fp)throw new QueryException("REQUEST_ID_CONFLICT","request_id was already used with different line arguments.");return old;}if(m_TransportOperations.Count>=128)throw new QueryException("TOO_MANY_OPERATIONS","This city session already contains 128 transport operations.");var op=new TransportLineOperation{Session=m_Session,RequestId=key,Fingerprint=fp,Type=type,Name=((string)args["name"]??"").Trim()};if(op.Name.Length>100)throw new QueryException("INVALID_ARGUMENT","name must contain at most 100 characters.");
            if(type=="create"){op.PrefabName=(string)args["line_prefab"]??"";op.Prefab=ResolveLinePrefab(op.PrefabName,world);}else{op.Target=ResolveLine(args,world);op.Prefab=world.EntityManager.GetComponentData<PrefabRef>(op.Target).m_Prefab;world.GetExistingSystemManaged<PrefabSystem>().TryGetPrefab<PrefabBase>(op.Prefab,out var pf);op.PrefabName=pf?.name;op.OriginalStops.AddRange(LineStops(world.EntityManager,op.Target));}
            if(type=="create"||type=="stops")op.Stops.AddRange(ParseStops(args["stop_ids"] as JArray,op.Prefab,world));else op.Stops.AddRange(op.OriginalStops);var rd=world.EntityManager.GetComponentData<RouteData>(op.Prefab);op.Color=rd.m_Color;if(args["color"] is JObject c)op.Color=new Color32((byte)c["r"],(byte)c["g"],(byte)c["b"],(byte?)c["a"]??(byte)255);
            m_TransportOperations.Add(op.Id,op);m_TransportRequestIds.Add(key,op.Id);world.GetOrCreateSystemManaged<McpTransportLineToolSystem>().Begin(op);return op;
        }
        private TransportLineOperation TransportOperationById(JObject args){string id=(string)args["operation_id"];if(id==null||!m_TransportOperations.TryGetValue(id,out var op))throw new QueryException("UNKNOWN_OPERATION","Unknown transport operation for this city session.");return op;}
        private JObject GetTransportOperation(JObject args,World world){var op=TransportOperationById(args);if(op.State=="completed"&&!op.NameApplied&&op.Result!=Entity.Null&&!string.IsNullOrWhiteSpace(op.Name)){world.GetOrCreateSystemManaged<Game.UI.NameSystem>().SetCustomName(op.Result,op.Name);op.NameApplied=true;}return op.Json();}
        private JObject ApplyTransportOperation(JObject args,World world){var op=TransportOperationById(args);if(RequestKey(args)!=op.RequestId)throw new QueryException("REQUEST_ID_CONFLICT","Use the preview request_id.");if(op.State=="completed")return GetTransportOperation(args,world);if(op.State!="preview_ready")throw new QueryException("INVALID_OPERATION_STATE","Only a preview_ready transport operation can be applied.");if(world.GetExistingSystemManaged<SimulationSystem>().selectedSpeed!=0)throw new QueryException("CITY_MUST_BE_PAUSED","Pause the city before applying a transport line operation.");op.CommitRequested=true;return op.Json();}
        private JObject CancelTransportOperation(JObject args){var op=TransportOperationById(args);if(op.ApplyDispatched)throw new QueryException("APPLY_ALREADY_DISPATCHED","The native apply has already been dispatched.");if(!op.Terminal)op.CancelRequested=true;return op.Json();}
        private JObject SetTransportLineName(JObject args,World world){var e=ResolveLine(args,world);string n=((string)args["name"]??"").Trim();if(n.Length>100)throw new QueryException("INVALID_ARGUMENT","name must contain at most 100 characters.");world.GetOrCreateSystemManaged<Game.UI.NameSystem>().SetCustomName(e,n);return new JObject{{"line_id",m_Session+":"+e.Index+":"+e.Version},{"name",string.IsNullOrWhiteSpace(n)?null:n}};}
        private JObject SetTransportLineActive(JObject args,World world){if(world.GetExistingSystemManaged<SimulationSystem>().selectedSpeed!=0)throw new QueryException("CITY_MUST_BE_PAUSED","Pause the city before changing line state.");var e=ResolveLine(args,world);bool active=(bool)args["active"];world.GetOrCreateSystemManaged<Game.UI.InGame.TransportationOverviewUISystem>().SetLineState(e,active);return new JObject{{"line_id",m_Session+":"+e.Index+":"+e.Version},{"requested_active",active},{"change_queued",true}};}
        private JObject SetTransportLineColor(JObject args,World world){var e=ResolveLine(args,world);var c=new Color32((byte)args["r"],(byte)args["g"],(byte)args["b"],(byte?)args["a"]??(byte)255);var em=world.EntityManager;em.SetComponentData(e,new Game.Routes.Color(c));if(em.HasBuffer<RouteVehicle>(e)){var b=em.GetBuffer<RouteVehicle>(e,true);for(int i=0;i<b.Length;i++)if(em.Exists(b[i].m_Vehicle)){if(em.HasComponent<Game.Routes.Color>(b[i].m_Vehicle))em.SetComponentData(b[i].m_Vehicle,new Game.Routes.Color(c));else em.AddComponentData(b[i].m_Vehicle,new Game.Routes.Color(c));}}var ev=em.CreateEntity(typeof(Game.Common.Event),typeof(ColorUpdated));em.SetComponentData(ev,new ColorUpdated(e));return new JObject{{"line_id",m_Session+":"+e.Index+":"+e.Version},{"color",new JObject{{"r",c.r},{"g",c.g},{"b",c.b},{"a",c.a}}}};}
        private UITransportConfigurationPrefab TransportConfiguration(World world)
        {
            var em=world.EntityManager;using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<UITransportConfigurationData>())){if(q.IsEmptyIgnoreFilter)throw new QueryException("TRANSPORT_CONFIGURATION_UNAVAILABLE","The native transport UI configuration is unavailable.");return world.GetExistingSystemManaged<PrefabSystem>().GetSingletonPrefab<UITransportConfigurationPrefab>(q);}
        }
        private Entity TransportPolicy(World world,Func<UITransportConfigurationPrefab,PolicyPrefab> selector){var ps=world.GetExistingSystemManaged<PrefabSystem>();var prefab=selector(TransportConfiguration(world));var e=ps.GetEntity(prefab);if(e==Entity.Null||!world.EntityManager.Exists(e))throw new QueryException("TRANSPORT_POLICY_UNAVAILABLE","The requested native transport policy is unavailable.");return e;}
        private JObject SetTransportLineSchedule(JObject args,World world)
        {
            RequirePaused(world);var e=ResolveLine(args,world);string schedule=((string)args["schedule"]??"day_and_night").ToLowerInvariant();if(schedule!="day"&&schedule!="night"&&schedule!="day_and_night")throw new QueryException("INVALID_ARGUMENT","schedule must be day, night, or day_and_night.");var ui=world.GetOrCreateSystemManaged<Game.UI.InGame.PoliciesUISystem>();var day=TransportPolicy(world,x=>x.m_DayRoutePolicy);var night=TransportPolicy(world,x=>x.m_NightRoutePolicy);ui.SetPolicy(e,day,schedule=="day");ui.SetPolicy(e,night,schedule=="night");return new JObject{{"line_id",EntityId(e)},{"requested_schedule",schedule},{"change_queued",true}};
        }
        private JObject SetTransportLineTicketPrice(JObject args,World world)
        {
            RequirePaused(world);var e=ResolveLine(args,world);int price=ComponentInspector.Int(args,"ticket_price",0,0,65535);var policy=TransportPolicy(world,x=>x.m_TicketPricePolicy);var em=world.EntityManager;if(!em.HasComponent<PolicySliderData>(policy))throw new QueryException("TRANSPORT_POLICY_UNAVAILABLE","The native ticket-price slider is unavailable.");var slider=em.GetComponentData<PolicySliderData>(policy);if(price>0&&(price<slider.m_Range.min||price>slider.m_Range.max))throw new QueryException("INVALID_ARGUMENT","ticket_price is outside the native slider range.");world.GetOrCreateSystemManaged<Game.UI.InGame.PoliciesUISystem>().SetPolicy(e,policy,price>0,price>0?price:slider.m_Default);var line=em.GetComponentData<TransportLine>(e);line.m_TicketPrice=(ushort)price;em.SetComponentData(e,line);return new JObject{{"line_id",EntityId(e)},{"requested_ticket_price",price},{"native_range",new JObject{{"min",slider.m_Range.min},{"max",slider.m_Range.max},{"step",slider.m_Step}}},{"change_queued",true},{"immediately_visible",true}};
        }
        private float StableLineDuration(EntityManager em,Entity line,TransportLineData data)
        {
            if(!em.HasBuffer<RouteWaypoint>(line)||!em.HasBuffer<RouteSegment>(line))return 0;var waypoints=em.GetBuffer<RouteWaypoint>(line,true);var segments=em.GetBuffer<RouteSegment>(line,true);int start=0;for(int i=0;i<waypoints.Length;i++)if(em.HasComponent<VehicleTiming>(waypoints[i].m_Waypoint)){start=i;break;}float duration=0;for(int j=0;j<waypoints.Length&&j<segments.Length;j++){int a=(start+j)%waypoints.Length,b=(a+1)%waypoints.Length;var segment=segments[a].m_Segment;if(em.HasComponent<PathInformation>(segment))duration+=em.GetComponentData<PathInformation>(segment).m_Duration;if(em.HasComponent<VehicleTiming>(waypoints[b].m_Waypoint))duration+=data.m_StopDuration;}return duration;
        }
        private int VehicleCountAtAdjustment(EntityManager em,Entity policy,float adjustment,float originalInterval,float duration)
        {
            var slider=em.GetComponentData<PolicySliderData>(policy);var modifier=default(RouteModifier);var datas=em.GetBuffer<RouteModifierData>(policy,true);for(int i=0;i<datas.Length;i++)if(datas[i].m_Type==RouteModifierType.VehicleInterval){var d=datas[i];float t=(adjustment-slider.m_Range.min)/math.max(.0001f,slider.m_Range.max-slider.m_Range.min);float delta=math.lerp(d.m_Range.min,d.m_Range.max,math.saturate(t));Game.Policies.RouteModifierInitializeSystem.RouteModifierRefreshData.AddModifierData(ref modifier,d,delta);break;}float interval=(originalInterval+modifier.m_Delta.x)*(1f+modifier.m_Delta.y);return TransportLineSystem.CalculateVehicleCount(interval,duration);
        }
        private JObject SetTransportLineVehicleCount(JObject args,World world)
        {
            RequirePaused(world);var e=ResolveLine(args,world);int count=ComponentInspector.Int(args,"vehicle_count",1,1,10000);var em=world.EntityManager;var prefab=em.GetComponentData<PrefabRef>(e).m_Prefab;var data=em.GetComponentData<TransportLineData>(prefab);float duration=StableLineDuration(em,e,data);if(duration<=0)throw new QueryException("TRANSPORT_LINE_DURATION_UNAVAILABLE","The line must have a completed path with duration data before setting vehicle count.");var policy=TransportPolicy(world,x=>x.m_VehicleCountPolicy);if(!em.HasComponent<PolicySliderData>(policy)||!em.HasBuffer<RouteModifierData>(policy))throw new QueryException("TRANSPORT_POLICY_UNAVAILABLE","The native vehicle-count policy slider is unavailable.");var slider=em.GetComponentData<PolicySliderData>(policy);int atMin=VehicleCountAtAdjustment(em,policy,slider.m_Range.min,data.m_DefaultVehicleInterval,duration),atMax=VehicleCountAtAdjustment(em,policy,slider.m_Range.max,data.m_DefaultVehicleInterval,duration);int min=math.min(atMin,atMax),max=math.max(atMin,atMax);if(count<min||count>max)throw new QueryException("INVALID_ARGUMENT","vehicle_count is outside the native line range "+min+".."+max+".");float lo=slider.m_Range.min,hi=slider.m_Range.max;for(int i=0;i<32;i++){float mid=(lo+hi)*.5f;int value=VehicleCountAtAdjustment(em,policy,mid,data.m_DefaultVehicleInterval,duration);if((atMax>=atMin&&value<count)||(atMax<atMin&&value>count))lo=mid;else hi=mid;}float adjustment=(lo+hi)*.5f;world.GetOrCreateSystemManaged<Game.UI.InGame.PoliciesUISystem>().SetPolicy(e,policy,true,adjustment);return new JObject{{"line_id",EntityId(e)},{"requested_vehicle_count",count},{"native_vehicle_count_range",new JObject{{"min",min},{"max",max}}},{"policy_adjustment",adjustment},{"stable_duration",duration},{"change_queued",true}};
        }
        private JObject SetTransportLineNumber(JObject args,World world){RequirePaused(world);var e=ResolveLine(args,world);int number=ComponentInspector.Int(args,"route_number",1,1,999999);var em=world.EntityManager;if(em.HasComponent<RouteNumber>(e))em.SetComponentData(e,new RouteNumber{m_Number=number});else em.AddComponentData(e,new RouteNumber{m_Number=number});return new JObject{{"line_id",EntityId(e)},{"route_number",number}};}
        private JObject SetTransportLineUnbunching(JObject args,World world){RequirePaused(world);var e=ResolveLine(args,world);float factor=BuildingNumber(args,"unbunching_factor",.75f,0,1);var em=world.EntityManager;var line=em.GetComponentData<TransportLine>(e);float before=line.m_UnbunchingFactor;line.m_UnbunchingFactor=factor;em.SetComponentData(e,line);return new JObject{{"line_id",EntityId(e)},{"before",before},{"unbunching_factor",factor}};}
        private JObject SetTransportStopName(JObject args,World world){var e=ResolveStopToken((string)args["stop_id"],world);string name=((string)args["name"]??"").Trim();if(name.Length>100)throw new QueryException("INVALID_ARGUMENT","name must contain at most 100 characters.");world.GetOrCreateSystemManaged<Game.UI.NameSystem>().SetCustomName(e,name);return new JObject{{"stop_id",EntityId(e)},{"name",string.IsNullOrWhiteSpace(name)?null:name}};}
        private JObject TransportRequestRow(EntityManager em,Entity request,string source)
        {
            var row=new JObject{{"request_id",EntityId(request)},{"source",source},{"exists",em.Exists(request)},{"deleted",em.Exists(request)&&em.HasComponent<Deleted>(request)}};if(em.Exists(request)&&em.HasComponent<TransportVehicleRequest>(request)){var r=em.GetComponentData<TransportVehicleRequest>(request);row["route_id"]=EntityId(r.m_Route);row["priority"]=r.m_Priority;}if(em.Exists(request)&&em.HasComponent<ServiceRequest>(request)){var r=em.GetComponentData<ServiceRequest>(request);row["fail_count"]=r.m_FailCount;row["cooldown"]=r.m_Cooldown;row["flags"]=r.m_Flags.ToString();}if(em.Exists(request)&&em.HasComponent<Dispatched>(request))row["handler_id"]=EntityId(em.GetComponentData<Dispatched>(request).m_Handler);return row;
        }
        private JObject ListTransportVehicleRequests(JObject args,World world)
        {
            var e=ResolveLine(args,world);var em=world.EntityManager;var line=em.GetComponentData<TransportLine>(e);var rows=new JArray();var seen=new HashSet<Entity>();if(line.m_VehicleRequest!=Entity.Null&&seen.Add(line.m_VehicleRequest))rows.Add(TransportRequestRow(em,line.m_VehicleRequest,"pending"));if(em.HasBuffer<DispatchedRequest>(e)){var b=em.GetBuffer<DispatchedRequest>(e,true);for(int i=0;i<b.Length;i++)if(b[i].m_VehicleRequest!=Entity.Null&&seen.Add(b[i].m_VehicleRequest))rows.Add(TransportRequestRow(em,b[i].m_VehicleRequest,"dispatched"));}return new JObject{{"line_id",EntityId(e)},{"total",rows.Count},{"items",rows}};
        }
        private JObject RequestTransportLineVehicle(JObject args,World world)
        {
            RequirePaused(world);var e=ResolveLine(args,world);float priority=BuildingNumber(args,"priority",1,0.001f,1);var em=world.EntityManager;var line=em.GetComponentData<TransportLine>(e);if(line.m_VehicleRequest!=Entity.Null&&em.Exists(line.m_VehicleRequest)&&!em.HasComponent<Deleted>(line.m_VehicleRequest))throw new QueryException("TRANSPORT_VEHICLE_REQUEST_PENDING","This line already has a pending native vehicle request.");var request=em.CreateEntity(typeof(ServiceRequest),typeof(TransportVehicleRequest),typeof(RequestGroup));em.SetComponentData(request,new ServiceRequest(false));em.SetComponentData(request,new TransportVehicleRequest(e,priority));em.SetComponentData(request,new RequestGroup(8));line.m_VehicleRequest=request;line.m_Flags|=TransportLineFlags.RequireVehicles;em.SetComponentData(e,line);return new JObject{{"line_id",EntityId(e)},{"request_id",EntityId(request)},{"priority",priority},{"native_request_queued",true}};
        }
        private JObject CancelTransportLineVehicleRequests(JObject args,World world)
        {
            RequirePaused(world);var e=ResolveLine(args,world);var em=world.EntityManager;var line=em.GetComponentData<TransportLine>(e);var requests=new HashSet<Entity>();if(line.m_VehicleRequest!=Entity.Null)requests.Add(line.m_VehicleRequest);if(em.HasBuffer<DispatchedRequest>(e)){var b=em.GetBuffer<DispatchedRequest>(e);for(int i=0;i<b.Length;i++)if(b[i].m_VehicleRequest!=Entity.Null)requests.Add(b[i].m_VehicleRequest);b.Clear();}int count=0;foreach(var r in requests)if(em.Exists(r)&&!em.HasComponent<Deleted>(r)){em.AddComponent<Deleted>(r);count++;}line.m_VehicleRequest=Entity.Null;line.m_Flags&=~TransportLineFlags.RequireVehicles;em.SetComponentData(e,line);return new JObject{{"line_id",EntityId(e)},{"cancelled_request_count",count},{"cleanup_queued",count>0}};
        }
        private JObject ReleaseTransportLineVehicle(JObject args,World world)
        {
            RequirePaused(world);var line=ResolveLine(args,world);var vehicle=ParseEntity((string)args["vehicle_id"],world.EntityManager);var em=world.EntityManager;bool found=false;if(em.HasBuffer<RouteVehicle>(line)){var b=em.GetBuffer<RouteVehicle>(line,true);for(int i=0;i<b.Length;i++)if(b[i].m_Vehicle==vehicle){found=true;break;}}if(!found)throw new QueryException("VEHICLE_NOT_ON_LINE","vehicle_id is not assigned to this transport line.");string kind;if(em.HasComponent<Game.Vehicles.PublicTransport>(vehicle)){var v=em.GetComponentData<Game.Vehicles.PublicTransport>(vehicle);v.m_State|=Game.Vehicles.PublicTransportFlags.AbandonRoute;em.SetComponentData(vehicle,v);kind="public_transport";}else if(em.HasComponent<Game.Vehicles.CargoTransport>(vehicle)){var v=em.GetComponentData<Game.Vehicles.CargoTransport>(vehicle);v.m_State|=Game.Vehicles.CargoTransportFlags.AbandonRoute;em.SetComponentData(vehicle,v);kind="cargo_transport";}else throw new QueryException("TRANSPORT_VEHICLE_STATE_UNAVAILABLE","The assigned vehicle has no public or cargo transport state.");return new JObject{{"line_id",EntityId(line)},{"vehicle_id",EntityId(vehicle)},{"vehicle_kind",kind},{"return_to_depot_requested",true}};
        }
        private IEnumerable<JObject> ReadRoutePolicies(World world,Entity line)
        {
            var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();DynamicBuffer<Game.Policies.Policy> current=default;bool hc=em.TryGetBuffer(line,true,out current);using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<PolicyData>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var p in es){if(!em.HasComponent<RouteOptionData>(p)&&!em.HasBuffer<RouteModifierData>(p))continue;if(!ps.TryGetPrefab<PrefabBase>(p,out var pf))continue;bool active=false;float adjustment=em.HasComponent<PolicySliderData>(p)?em.GetComponentData<PolicySliderData>(p).m_Default:0;if(hc)for(int i=0;i<current.Length;i++)if(current[i].m_Policy==p){active=(current[i].m_Flags&Game.Policies.PolicyFlags.Active)!=0;adjustment=current[i].m_Adjustment;break;}var row=new JObject{{"name",pf.name},{"active",active},{"adjustment",adjustment},{"locked",RoadOperation.IsLocked(em,p)}};if(em.HasComponent<RouteOptionData>(p))row["option_mask"]=em.GetComponentData<RouteOptionData>(p).m_OptionMask;if(em.HasComponent<PolicySliderData>(p)){var s=em.GetComponentData<PolicySliderData>(p);row["slider"]=new JObject{{"min",s.m_Range.min},{"max",s.m_Range.max},{"default",s.m_Default},{"step",s.m_Step},{"unit",s.m_Unit}};}yield return row;}
        }
        private JObject ListTransportLinePolicies(JObject args,World world){var e=ResolveLine(args,world);return new JObject{{"line_id",m_Session+":"+e.Index+":"+e.Version},{"items",new JArray(ReadRoutePolicies(world,e).OrderBy(x=>(string)x["name"]))}};}
        private JObject SetTransportLinePolicy(JObject args,World world){if(world.GetExistingSystemManaged<SimulationSystem>().selectedSpeed!=0)throw new QueryException("CITY_MUST_BE_PAUSED","Pause the city before changing line policy.");var e=ResolveLine(args,world);string wanted=(string)args["policy"]??"";var em=world.EntityManager;Entity selected=Entity.Null;PrefabBase pf=null;using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<PolicyData>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var p in es)if((em.HasComponent<RouteOptionData>(p)||em.HasBuffer<RouteModifierData>(p))&&world.GetExistingSystemManaged<PrefabSystem>().TryGetPrefab<PrefabBase>(p,out var x)&&string.Equals(x.name,wanted,StringComparison.OrdinalIgnoreCase)){selected=p;pf=x;break;}if(selected==Entity.Null)throw new QueryException("ROUTE_POLICY_NOT_FOUND","Use an exact name from list_transport_line_policies.");if(RoadOperation.IsLocked(em,selected))throw new QueryException("ROUTE_POLICY_LOCKED","The policy is locked.");bool active=(bool)args["active"];float adj=(float?)args["adjustment"]??(em.HasComponent<PolicySliderData>(selected)?em.GetComponentData<PolicySliderData>(selected).m_Default:0);if(em.HasComponent<PolicySliderData>(selected)){var s=em.GetComponentData<PolicySliderData>(selected);if(adj<s.m_Range.min||adj>s.m_Range.max)throw new QueryException("INVALID_ARGUMENT","adjustment is outside the slider range.");}else if(math.abs(adj)>.0001f)throw new QueryException("INVALID_ARGUMENT","This policy has no slider.");world.GetOrCreateSystemManaged<Game.UI.InGame.PoliciesUISystem>().SetPolicy(e,selected,active,adj);return new JObject{{"line_id",m_Session+":"+e.Index+":"+e.Version},{"policy",pf.name},{"requested_active",active},{"requested_adjustment",adj},{"change_queued",true}};}
    }
}

