using System;
using System.Collections.Generic;
using System.Linq;
using Colossal.Mathematics;
using Game.Buildings;
using Game.Common;
using Game.Net;
using Game.Prefabs;
using Game.Simulation;
using Game.Tools;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;

namespace CityWeaver
{
    public sealed partial class GameQueryService
    {
        private Entity[] WaterwayPrefabs(EntityManager em){using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<WaterwayData>(),ComponentType.ReadOnly<NetData>(),ComponentType.ReadOnly<NetGeometryData>(),ComponentType.ReadOnly<PlaceableNetData>(),ComponentType.ReadOnly<PrefabData>()))using(var es=q.ToEntityArray(Allocator.Temp))return es.ToArray();}
        private Entity ResolveWaterwayPrefab(string wanted,World world){var ps=world.GetExistingSystemManaged<PrefabSystem>();foreach(var e in WaterwayPrefabs(world.EntityManager))if(ps.TryGetPrefab<PrefabBase>(e,out var p)&&p is NetPrefab&&string.Equals(p.name,wanted,StringComparison.OrdinalIgnoreCase))return e;throw new QueryException("WATERWAY_PREFAB_NOT_FOUND","Use an exact name from list_waterway_prefabs.");}
        private JObject ListWaterwayPrefabs(JObject args,World world)
        {
            string search=((string)args["search"]??"").Trim(),type=((string)args["waterway_type"]??"").Trim();bool unlocked=(bool?)args["unlocked_only"]??true;var rows=new List<JObject>();var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();
            foreach(var e in WaterwayPrefabs(em)){if(!ps.TryGetPrefab<PrefabBase>(e,out var p)||!(p is NetPrefab)||search.Length>0&&p.name.IndexOf(search,StringComparison.OrdinalIgnoreCase)<0)continue;var td=em.GetComponentData<WaterwayData>(e);if(type.Length>0&&!string.Equals(type,"Ship",StringComparison.OrdinalIgnoreCase))continue;bool locked=RoadOperation.IsLocked(em,e);if(unlocked&&locked)continue;var g=em.GetComponentData<NetGeometryData>(e);var place=em.GetComponentData<PlaceableNetData>(e);rows.Add(new JObject{{"name",p.name},{"waterway_type","Ship"},{"speed_limit_mps",td.m_SpeedLimit},{"locked",locked},{"width_m",g.m_DefaultWidth},{"max_slope",g.m_MaxSlopeSteepness},{"edge_length_m",new JObject{{"min",g.m_EdgeLengthRange.min},{"max",g.m_EdgeLengthRange.max}}},{"elevation_range_m",new JObject{{"min",place.m_ElevationRange.min},{"max",place.m_ElevationRange.max}}},{"construction_cost_per_m",place.m_DefaultConstructionCost},{"placement_flags",place.m_PlacementFlags.ToString()}});}
            return new JObject{{"total",rows.Count},{"items",new JArray(rows.OrderBy(x=>(string)x["name"]))}};
        }
        private bool IsPermanentWaterway(EntityManager em,Entity e)=>em.Exists(e)&&em.HasComponent<Game.Net.Waterway>(e)&&em.HasComponent<Edge>(e)&&em.HasComponent<Curve>(e)&&em.HasComponent<PrefabRef>(e)&&!em.HasComponent<Temp>(e)&&!em.HasComponent<Deleted>(e)&&em.HasComponent<WaterwayData>(em.GetComponentData<PrefabRef>(e).m_Prefab);
        private JObject WaterwayRow(World world,Entity e,bool detail){var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();var p=em.GetComponentData<PrefabRef>(e).m_Prefab;ps.TryGetPrefab<PrefabBase>(p,out var pf);var td=em.GetComponentData<WaterwayData>(p);var curve=em.GetComponentData<Curve>(e);var edge=em.GetComponentData<Edge>(e);var row=new JObject{{"waterway_edge_id",m_Session+":"+e.Index+":"+e.Version},{"prefab",pf?.name},{"waterway_type","Ship"},{"speed_limit_mps",td.m_SpeedLimit},{"length_m",curve.m_Length},{"start",PointJson(curve.m_Bezier.a)},{"end",PointJson(curve.m_Bezier.d)},{"start_node_id",m_Session+":"+edge.m_Start.Index+":"+edge.m_Start.Version},{"end_node_id",m_Session+":"+edge.m_End.Index+":"+edge.m_End.Version}};if(detail){row["curve"]=new JObject{{"a",PointJson(curve.m_Bezier.a)},{"b",PointJson(curve.m_Bezier.b)},{"c",PointJson(curve.m_Bezier.c)},{"d",PointJson(curve.m_Bezier.d)}};if(em.HasComponent<Elevation>(e)){var x=em.GetComponentData<Elevation>(e).m_Elevation;row["elevation_m"]=new JObject{{"start",x.x},{"end",x.y}};}row["owned_by"]=em.HasComponent<Owner>(e)?m_Session+":"+em.GetComponentData<Owner>(e).m_Owner.Index+":"+em.GetComponentData<Owner>(e).m_Owner.Version:null;}return row;}
        private JObject ListWaterways(JObject args,World world){string type=((string)args["waterway_type"]??"").Trim();var rows=new List<JObject>();var em=world.EntityManager;using(var q=em.CreateEntityQuery(ComponentType.ReadOnly<Edge>(),ComponentType.ReadOnly<Curve>(),ComponentType.ReadOnly<PrefabRef>(),ComponentType.Exclude<Deleted>(),ComponentType.Exclude<Temp>()))using(var es=q.ToEntityArray(Allocator.Temp))foreach(var e in es)if(IsPermanentWaterway(em,e)){var r=WaterwayRow(world,e,false);if(type.Length==0||string.Equals(type,(string)r["waterway_type"],StringComparison.OrdinalIgnoreCase))rows.Add(r);}return new JObject{{"total",rows.Count},{"items",new JArray(rows)}};}
        private JObject GetWaterway(JObject args,World world){var e=ParseEntity((string)args["waterway_edge_id"],world.EntityManager);if(!IsPermanentWaterway(world.EntityManager,e))throw new QueryException("WATERWAY_NOT_FOUND","waterway_edge_id must identify a permanent waterway.");return WaterwayRow(world,e,true);}
        private RoadEndpoint WaterwayPoint(JObject value,World world,Game.Simulation.TerrainHeightData heights)
        {
            if(value==null)throw new QueryException("INVALID_ARGUMENT","Each point requires x and z.");var em=world.EntityManager;if(value["x"]==null||value["z"]==null||value["elevation_m"]!=null)throw new QueryException("INVALID_ARGUMENT","Waterway points require x/z and do not accept elevation_m.");float elevation=0;var pos=new float3(BuildingNumber(value,"x",0,-7168,7168),0,BuildingNumber(value,"z",0,-7168,7168));Entity target=Entity.Null;float split=0;
            if(value["node_id"]!=null&&value["edge_id"]!=null)throw new QueryException("INVALID_ARGUMENT","Use node_id or edge_id, not both.");
            if(value["node_id"]!=null){target=ParseEntity((string)value["node_id"],em);if(!em.HasComponent<Node>(target)||em.HasComponent<Deleted>(target)||em.HasComponent<Temp>(target))throw new QueryException("INVALID_WATERWAY_NODE","node_id must identify a permanent network node.");bool track=false;if(em.HasBuffer<ConnectedEdge>(target)){var b=em.GetBuffer<ConnectedEdge>(target,true);for(int i=0;i<b.Length;i++)if(IsPermanentWaterway(em,b[i].m_Edge)){track=true;break;}}if(!track)throw new QueryException("INVALID_WATERWAY_NODE","node_id is not connected to a waterway.");pos=em.GetComponentData<Node>(target).m_Position;}
            else if(value["edge_id"]!=null){target=ParseEntity((string)value["edge_id"],em);if(!IsPermanentWaterway(em,target))throw new QueryException("INVALID_WATERWAY_EDGE","edge_id must identify a permanent waterway.");var c=em.GetComponentData<Curve>(target).m_Bezier;MathUtils.Distance(c.xz,pos.xz,out split);pos=MathUtils.Position(c,split);if(math.distance(pos.xz,new float2(BuildingNumber(value,"x",0,-7168,7168),BuildingNumber(value,"z",0,-7168,7168)))>8)throw new QueryException("INVALID_WATERWAY_EDGE","The requested point must be within 8 metres of edge_id.");}
            else { var water=world.GetExistingSystemManaged<WaterSystem>().GetSurfaceData(out var deps); deps.Complete(); if(!water.isCreated)throw new QueryException("WATER_UNAVAILABLE","Water data is unavailable."); bool wet; pos.y=WaterUtils.SampleHeight(ref water,ref heights,pos,out wet); if(!wet)throw new QueryException("WATERWAY_REQUIRES_WATER","New endpoints must be on water."); }
            if(target!=Entity.Null&&math.abs(elevation)>.01f)throw new QueryException("INVALID_ENDPOINT","Attached waterway endpoints inherit their current elevation.");return new RoadEndpoint{Position=pos,Target=target,Split=split,Elevation=elevation};
        }
        private void ValidateWaterwayCurve(Bezier4x3 curve, Entity prefab, World world, float minimumDepth)
        {
            var em=world.EntityManager;var geometry=em.GetComponentData<NetGeometryData>(prefab);
            float length=MathUtils.Length(curve), maximum=geometry.m_EdgeLengthRange.max;
            if(!math.isfinite(length)||length<math.max(16,geometry.m_EdgeLengthRange.min)||length>(maximum>0?maximum:1024))
                throw new QueryException("INVALID_WATERWAY_LENGTH","Segment length must satisfy the selected prefab limits.");
            var terrain=world.GetExistingSystemManaged<TerrainSystem>().GetHeightData(true);
            var water=world.GetExistingSystemManaged<WaterSystem>().GetSurfaceData(out var deps);deps.Complete();
            if(!terrain.isCreated||!water.isCreated)throw new QueryException("WATER_UNAVAILABLE","Terrain/water samples are unavailable.");
            int samples=(int)math.ceil(length/8);float halfWidth=geometry.m_DefaultWidth*.5f;
            for(int i=0;i<=samples;i++)
            {
                float t=i/(float)samples;var p=MathUtils.Position(curve,t);
                var tangent=3*(1-t)*(1-t)*(curve.b-curve.a)+6*(1-t)*t*(curve.c-curve.b)+3*t*t*(curve.d-curve.c);
                if(math.lengthsq(tangent.xz)<.0001f)throw new QueryException("INVALID_WATERWAY_CURVE","Waterway curve has a cusp.");
                var side=math.normalize(new float2(-tangent.z,tangent.x));
                for(int j=-2;j<=2;j++)
                {
                    var q=new float3(p.x+side.x*halfWidth*j/2,0,p.z+side.y*halfWidth*j/2);
                    float depth=WaterUtils.SampleDepth(ref water,q);
                    if(!math.isfinite(depth)||depth<minimumDepth)throw new QueryException("SHALLOW_WATERWAY","The sampled waterway width crosses dry or shallow water.");
                }
            }
        }
        private JObject WaterwayOperationJson(RoadOperation op){var j=op.Json();j["waterway_prefab"]=op.PrefabName;j["minimum_water_depth_m"]=op.MinimumWaterDepth;j["created_waterway_ids"]=j["created_road_ids"]?.DeepClone()??new JArray();j["target_waterway_edge_ids"]=j["target_edge_ids"]?.DeepClone()??new JArray();j["curve_segments"]=new JArray(op.Segments.Select(s=>new JObject{{"a",RoadOperation.Point(s.Curve.a)},{"b",RoadOperation.Point(s.Curve.b)},{"c",RoadOperation.Point(s.Curve.c)},{"d",RoadOperation.Point(s.Curve.d)},{"sampled_min_radius_m",double.IsInfinity(TrackCurveRadius(s.Curve))?JValue.CreateNull():new JValue(TrackCurveRadius(s.Curve))}}));j["note"]="A preview is temporary. Only completed confirms permanent waterway edges.";return j;}
        private JObject PreviewWaterway(JObject args,World world)
        {
            string key=RequestKey(args),fingerprint=new JObject{{"kind","waterway"},{"waterway_prefab",args["waterway_prefab"]?.DeepClone()},{"points",args["points"]?.DeepClone()},{"curves",args["curves"]?.DeepClone()},{"min_radius_m",args["min_radius_m"]?.DeepClone()},{"minimum_water_depth_m",args["minimum_water_depth_m"]?.DeepClone()}}.ToString(Formatting.None);if(m_RoadRequestIds.TryGetValue(key,out var oldId)){var old=m_RoadOperations[oldId];if(old.Fingerprint!=fingerprint)throw new QueryException("IDEMPOTENCY_CONFLICT","request_id already belongs to another operation.");if(old.TransactionKind!="waterway")throw new QueryException("IDEMPOTENCY_CONFLICT","request_id belongs to a road operation.");return WaterwayOperationJson(old);}if(!(args["points"] is JArray points)||points.Count<2||points.Count>16)throw new QueryException("INVALID_ARGUMENT","points must contain 2..16 waterway points.");if(world.GetExistingSystemManaged<SimulationSystem>().selectedSpeed!=0)throw new QueryException("CITY_MUST_BE_PAUSED","Pause the city before previewing waterways.");if(m_RoadOperations.Count>=4096)throw new QueryException("ROAD_OPERATION_LIMIT","This city session has reached 4096 road operations; reload the city to reset the journal.");var tool=RoadTool(world);if(tool.Busy||!(world.GetExistingSystemManaged<ToolSystem>().activeTool is DefaultToolSystem))throw new QueryException("TOOL_BUSY","Select the default tool and finish another preview.");var em=world.EntityManager;var prefab=ResolveWaterwayPrefab((string)args["waterway_prefab"],world);if(RoadOperation.IsLocked(em,prefab))throw new QueryException("WATERWAY_PREFAB_LOCKED","The selected track prefab is locked.");var heights=world.GetExistingSystemManaged<TerrainSystem>().GetHeightData(true);if(!heights.isCreated)throw new QueryException("TERRAIN_UNAVAILABLE","Terrain heights are unavailable.");var curves=args["curves"] as JArray;
            if(args["curves"]!=null && curves==null) throw new QueryException("INVALID_ARGUMENT","curves must be an array.");
            if(curves!=null && curves.Count!=points.Count-1) throw new QueryException("INVALID_ARGUMENT","curves must contain one control specification (or null for straight) per segment.");
            float minimumRadius=BuildingNumber(args,"min_radius_m",curves!=null?150:0,0,5000);
            var parsed=points.Select(x=>WaterwayPoint(x as JObject,world,heights)).ToList();var op=new RoadOperation{Session=m_Session,RequestId=key,Fingerprint=fingerprint,OperationType="create",TransactionKind="waterway",MinimumWaterDepth=BuildingNumber(args,"minimum_water_depth_m",2,.1f,100),Prefab=prefab,PrefabName=(string)args["waterway_prefab"],CurveMode=curves!=null?"bezier_chain":"polyline"};for(int i=0;i+1<parsed.Count;i++){var a=parsed[i];var b=parsed[i+1];if(a.Target!=Entity.Null&&a.Target==b.Target&&math.abs(a.Split-b.Split)<.001f)throw new QueryException("INVALID_ENDPOINT","Adjacent points resolve to the same track position.");if(curves!=null && curves[i].Type!=JTokenType.Null && !(curves[i] is JObject)) throw new QueryException("INVALID_ARGUMENT","Each curve must be an object or null.");
                var c=TransportTrackCurve(curves?[i] as JObject,a,b);
                ValidateWaterwayCurve(c,prefab,world,op.MinimumWaterDepth);
                if(minimumRadius>0 && TrackCurveRadius(c)<minimumRadius) throw new QueryException("WATERWAY_RADIUS_TOO_SMALL","Waterway horizontal radius is smaller than min_radius_m, or the curve has a cusp.");
                if((curves!=null || minimumRadius>0) && i>0) {var previous=op.Segments[i-1].Curve;ValidateTrackJoin((previous.d-previous.c).xz,(c.b-c.a).xz);}
                op.Segments.Add(new RoadSegmentPlan{Start=a.Position,End=b.Position,StartTarget=a.Target,EndTarget=b.Target,StartSplit=a.Split,EndSplit=b.Split,StartElevation=a.Elevation,EndElevation=b.Elevation,Curve=c});}var first=op.Segments[0];var last=op.Segments[op.Segments.Count-1];op.Start=first.Start;op.End=last.End;op.StartNode=first.StartTarget;op.EndNode=last.EndTarget;op.StartSplit=first.StartSplit;op.EndSplit=last.EndSplit;op.StartElevation=first.StartElevation;op.EndElevation=last.EndElevation;op.Curve=first.Curve;tool.Begin(op);m_RoadOperations.Add(op.Id,op);m_RoadRequestIds.Add(key,op.Id);return WaterwayOperationJson(op);
        }
        private JObject PreviewWaterwayDelete(JObject args,World world)
        {
            string key=RequestKey(args),fingerprint=new JObject{{"kind","waterway_delete"},{"waterway_edge_ids",args["waterway_edge_ids"]?.DeepClone()}}.ToString(Formatting.None);if(m_RoadRequestIds.TryGetValue(key,out var oldId)){var old=m_RoadOperations[oldId];if(old.Fingerprint!=fingerprint||old.TransactionKind!="waterway")throw new QueryException("IDEMPOTENCY_CONFLICT","request_id belongs to another operation.");return WaterwayOperationJson(old);}if(!(args["waterway_edge_ids"] is JArray ids)||ids.Count<1||ids.Count>64)throw new QueryException("INVALID_ARGUMENT","waterway_edge_ids must contain 1..64 waterways.");if(world.GetExistingSystemManaged<SimulationSystem>().selectedSpeed!=0)throw new QueryException("CITY_MUST_BE_PAUSED","Pause the city before deleting waterways.");if(m_RoadOperations.Count>=4096)throw new QueryException("ROAD_OPERATION_LIMIT","This city session has reached 4096 road operations; reload the city to reset the journal.");var tool=RoadTool(world);if(tool.Busy||!(world.GetExistingSystemManaged<ToolSystem>().activeTool is DefaultToolSystem))throw new QueryException("TOOL_BUSY","Select the default tool and finish another preview.");var em=world.EntityManager;var ps=world.GetExistingSystemManaged<PrefabSystem>();var op=new RoadOperation{Session=m_Session,RequestId=key,Fingerprint=fingerprint,OperationType="batch_demolish",TransactionKind="waterway",CurveMode="existing"};var unique=new HashSet<Entity>();foreach(var token in ids){var e=ParseEntity((string)token,em);if(!unique.Add(e))throw new QueryException("DUPLICATE_WATERWAY_EDGE","waterway_edge_ids must be unique.");if(!IsPermanentWaterway(em,e))throw new QueryException("WATERWAY_NOT_FOUND","Every ID must identify a permanent waterway.");if(em.HasComponent<Owner>(e))throw new QueryException("OWNED_WATERWAY","Delete the owning facility instead of its internal waterway.");var p=em.GetComponentData<PrefabRef>(e).m_Prefab;ps.TryGetPrefab<PrefabBase>(p,out var pf);var edge=em.GetComponentData<Edge>(e);var curve=em.GetComponentData<Curve>(e).m_Bezier;var elevation=em.HasComponent<Elevation>(e)?em.GetComponentData<Elevation>(e).m_Elevation:new float2(0);op.TargetEdges.Add(e);op.Segments.Add(new RoadSegmentPlan{TargetEdge=e,OriginalPrefab=p,OriginalPrefabName=pf?.name,Start=curve.a,End=curve.d,StartTarget=edge.m_Start,EndTarget=edge.m_End,StartElevation=elevation.x,EndElevation=elevation.y,Curve=curve});}var f=op.Segments[0];var l=op.Segments[op.Segments.Count-1];op.TargetEdge=op.TargetEdges[0];op.Prefab=f.OriginalPrefab;op.PrefabName=f.OriginalPrefabName;op.OriginalPrefabName=f.OriginalPrefabName;op.Start=f.Start;op.End=l.End;op.StartNode=f.StartTarget;op.EndNode=l.EndTarget;op.Curve=f.Curve;tool.Begin(op);m_RoadOperations.Add(op.Id,op);m_RoadRequestIds.Add(key,op.Id);return WaterwayOperationJson(op);
        }
        private RoadOperation WaterwayOperation(JObject args){var op=RoadOperationById(args);if(op.TransactionKind!="waterway")throw new QueryException("WATERWAY_OPERATION_NOT_FOUND","operation_id does not identify a waterway operation.");return op;}
        private JObject GetWaterwayOperation(JObject args){return WaterwayOperationJson(WaterwayOperation(args));}
        private JObject ApplyWaterwayOperation(JObject args,World world){WaterwayOperation(args);return WaterwayOperationJsonAfter(CommitRoad(args));}
        private JObject WaterwayOperationJsonAfter(JObject ignored){var op=m_RoadOperations[(string)ignored["operation_id"]];return WaterwayOperationJson(op);}
        private JObject CancelWaterwayOperation(JObject args){var op=WaterwayOperation(args);CancelRoad(args);return WaterwayOperationJson(op);}
    }
}
