import json,math
from pathlib import Path
root=Path('artifacts');q=json.loads((root/'auburn-metro-relocation-audit.json').read_text(encoding='utf8'));removed=json.loads((root/'auburn-metro-old-loop-removal.json').read_text(encoding='utf8'));rows=[json.loads(l) for l in (root/'auburn-metro-relocation.jsonl').read_text(encoding='utf8').splitlines() if l];newcost=sum(r['result']['cost'] for r in rows if r.get('stage')=='completed');netcost=newcost+removed['result']['cost'];tiles=json.loads((root/'auburn-metro-feasibility.json').read_text())['tiles']['items'];depot=q['facilities'][-1]['facility'];vehicles=q['line']['vehicles']
def curve(c):
 a,b,e,d=[c[k] for k in ('a','b','c','d')];return f'M {a["x"]} {-a["z"]} C {b["x"]} {-b["z"]} {e["x"]} {-e["z"]} {d["x"]} {-d["z"]}'
def svg(detail=False):
 box='5900 -2750 1150 1550' if detail else '-850 -3150 8100 3800';s=f'<svg viewBox="{box}" role="img" aria-label="地铁迁建后的实际轨道"><rect x="-850" y="-3500" width="8100" height="4200" fill="#e9eee7"/>'
 for tile in tiles:
  b=tile['bounds'];s+=f'<rect x="{b["min_x"]}" y="{-b["max_z"]}" width="{b["max_x"]-b["min_x"]}" height="{b["max_z"]-b["min_z"]}" fill="none" stroke="#d6dfd2" stroke-width="2"/>'
 if detail:
  s+='<path d="M6500 -1100 L6500 -2030 M6500 -1600 L6600 -1600 M6600 -1400 L6600 -2200" fill="none" stroke="#a6afb5" stroke-width="24"/><text x="6520" y="-1440" font-size="22">原机场道路</text>'
 for t in removed['selected']:s+=f'<path class="removed" d="{curve(t["curve"])}" fill="none" stroke="#d58480" stroke-width="{5 if detail else 13}" stroke-dasharray="14 10"/>'
 for t in q['live_tracks']:
  owner=t.get('owned_by');color='#777f83' if owner==depot['facility_id'] else '#137e9b';s+=f'<path d="{curve(t["curve"])}" fill="none" stroke="{color}" stroke-width="{3 if owner and detail else 6 if detail else 15}"/>'
 for f in q['facilities']:
  fac=f['facility'];x=fac['position']['x'];z=fac['position']['z'];name='新地铁总站' if f['id']=='depot' else f['id'];size=20 if detail else 65
  if f['id']=='depot':s+=f'<rect x="{x-80}" y="{-z-176}" width="160" height="352" fill="#e9b659" fill-opacity=".2" stroke="#b78226" stroke-width="4"/>'
  s+=f'<circle cx="{x}" cy="{-z}" r="{12 if detail else 32}" fill="#d29b3f"/><text x="{x+25}" y="{-z-25}" font-size="{size}">{name}</text>'
 if detail:s+='<circle cx="6202.573" cy="-2457.985" r="14" fill="#d58480"/><text x="6230" y="-2457" font-size="22">总站原址（已迁走）</text>'
 return s+'</svg>'
table=''.join(f'<tr><td>{f["facility"]["name"]}</td><td>已连接</td><td>供电、给水、污水正常</td></tr>' for f in q['facilities'])
html=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>两镇地铁 · 总站迁建竣工图</title><style>body{{margin:0;background:#eef2ed;color:#203d45;font:16px/1.75 system-ui}}main{{max-width:1180px;margin:auto;padding:30px}}h1{{font-size:34px;line-height:1.4}}section{{background:white;border-radius:16px;padding:26px;margin:22px 0}}nav a{{margin-right:22px;color:#147891}}svg{{width:100%;max-height:720px}}.stats{{display:flex;gap:18px;flex-wrap:wrap}}.stats div{{flex:1;min-width:170px;background:#e5f0ee;padding:16px;border-radius:10px}}strong{{display:block;font-size:27px;color:#137e9b}}td,th{{padding:10px;text-align:left;border-bottom:1px solid #ddd}}table{{width:100%}}.note{{color:#627b80}}button{{border:1px solid #aac2c1;background:#f4f8f7;border-radius:8px;padding:9px 16px;cursor:pointer}}.hide-removed .removed{{display:none}}</style><main><small>奥本山 · 实体回读竣工图 · 2026-09-20</small><h1>总站已迁至原机场道路旁，M1 已发车</h1><nav><a href="#depot">总站新址</a><a href="#construction">施工与费用</a><a href="#line">线路验收</a></nav><div class="stats"><div><strong>4 座地下车站</strong>小镇1—小镇2往返</div><div><strong>{len(vehicles)} 列已上线</strong>已观察到列车移动、载客</div><div><strong>{removed['length_m']/1000:.2f} 公里</strong>拆除原总站冗余绕线</div><div><strong>{netcost:,}</strong>本轮净新增建设费用</div></div><section id="depot"><h2>横向临路的新总站</h2><p>位置约 <b>({depot['position']['x']:.1f}, {depot['position']['z']:.1f})</b>，位于原机场预留道路旁。总站长边与南北向道路平行，入口绑定 x=6600 的道路；四组库线均接入同一地铁网络。</p><button onclick="document.body.classList.toggle('hide-removed')">显示／隐藏已拆旧线</button>{svg(True)}<p class="note">蓝色：保留或新建轨道；灰色：总站内部轨道；红色虚线：已拆除。此图北向上，游戏镜头旋转时左右方向会不同。</p></section><section id="line"><h2>M1 小镇1—小镇2</h2>{svg()}<p>四座地下车站、六个往返停靠点，原生线路往返距离约 <b>{q['line']['route_distance_m']/1000:.2f} 公里</b>。客运主线保持地下；总站内轨道和入库口为地面部分。</p><p>已观察到列车实际出库、进入客运线并载客。这是初始运营验收，尚未完成全日客流和完整往返周期测试。</p></section><section id="construction"><h2>搬迁、接轨与清理</h2><table><tr><th>项目</th><th>结果</th><th>费用</th></tr><tr><td>原总站迁移</td><td>原生移动完成，入口绑定通过</td><td>0</td></tr><tr><td>新址主接入线与库线连接</td><td>全部建成，所有库线与四站连通</td><td>{newcost:,}</td></tr><tr><td>原入库绕线拆除</td><td>23段，约{removed['length_m']:.0f}米，永久回读确认移除</td><td>{removed['result']['cost']:,}</td></tr><tr><td>本轮净新增</td><td>保留东站前可复用轨道</td><td>{netcost:,}</td></tr></table><p>新址新增曲线的永久回读采样半径均超过150米；最后一组库线在首次交汇位置设置道岔，避免交叉重复铺轨。客运主线和车站未拆除。完成测试后游戏恢复暂停。</p><table><tr><th>设施</th><th>道路入口</th><th>管网</th></tr>{table}</table><p><a href="auburn-metro-relocation-audit.json">当前实体与运营回读</a> · <a href="auburn-metro-old-loop-removal.json">旧线拆除记录</a> · <a href="auburn-metro-relocation.jsonl">迁建接轨日志</a></p></section></main></html>'''
p=root/'auburn-metro-feasibility.html';p.write_text(html,encoding='utf8');print(json.dumps({'net_cost':netcost,'removed':removed['length_m'],'vehicles':len(vehicles)}))
